---
title: "BIOL 210 Course Agenda"
date: "Week 6, Sep 28-Oct 2"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# Reminders

* [Mastery project guidelines](https://docs.google.com/document/d/1IUTTWkps2DtSqaLAJ9bqXMkZg3bKnIn96g-EgX5o1Ag/edit?usp=sharing) are now live! 

    * Note that the project proposal is due Oct 10. <br><br>

* [Link to in-class slides and handouts](https://drive.google.com/drive/folders/17Fm-yEXqtlvGJfFaw6WqywIScW_eZ8m_?usp=drive_link)

* Midterm Reflection is coming up -- complete and meet with me by Oct 9. You can access the [reflection document here](https://docs.google.com/document/d/1Vvhn4R1gUjuunrFFWENReMvucvyaIbzeEJFK0aUpw4M/edit?usp=sharing). The link to my reflection calendar is in the doc. We'll have a 5-min meeting to discuss your responses.

* Exam 1 material finished Sep 25. Exam 1 is due Oct 2, end of day. [Exam 1 available here.](https://docs.google.com/document/d/1X0N-TC_iPrui603tfLdMv-AssXTBiAGCyMsRqdE-Auo/edit?usp=sharing)

    * Exams are short-answer, open-note, open-book, untimed. 
    * Use of internet searches not permitted. 
    * Do not discuss with anyone but Angie.
    * Designed to be completed within 75 minutes for a well-prepared student.<br><br>

* NEW TEAMS are assigned. Here they are (coral reef themed):
    * <b>Clownfish:</b> Kingston, Chaya, Maggi, Marko
    * <b>Corals:</b> Devin, Olivia, Bix, Shaswat
    * <b>Giant clams:</b> Ari, Rafael, Andrea, Hannah
    * <b>Moray eels:</b> Lii, John, Maeve
    * <b>Parrotfish:</b>  Leo S., Leo D., Eleana, Phoebe
    * <b>Pufferfish:</b> Zach, Bobby, Sylvia, Bird
    * <b>Sea cucumbers:</b> Asha, Aoife, Zoe, Ryan
    * <b>Sea lions:</b> David, Rose, Max, Izzy
    * <b>Sea turtles:</b> Ava, Nolan, Peyton, Ashlyn
    * <b>Wrasse:</b> Manolis, Giulia, August, James

# Content Videos

* [16-Dominance principle](https://drive.google.com/drive/folders/1xn0bdgGBMCf0MJvxNHW1BvSkR9U9smSV?usp=drive_link)

* [17-Independent assortment](https://drive.google.com/drive/folders/1xqGv2vUAJwJStXo54SmjDI1Y61viy_ly?usp=drive_link)

* [18-Linkage](https://drive.google.com/drive/folders/1Z4s_dBsSBdqrfdeumUCtSz3yI8XpOKwA?usp=drive_link)

# Assignments

[Quiz 5](https://docs.google.com/document/d/1nDCl4QiLlyYf7ejYQkAaCKIRqK_1BXKkiVoA5xDwAT0/edit?usp=sharing)

[Problem Set 6](ps6.html)

# Class Meetings

## Mon Sep 28

Case study on alternative splicing.

## Wed Sep 30

Finish case study on alternative splicing.

If time allows, work on genetics problems.

## Fri Oct 2

Quiz 5, first solo then corrections with teams.
<br>

------------------------------------------------------------------------
