---
title: "BIOL 210 Course Agenda"
date: "Week 5, Sep 21-25"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# Reminders

* [Mastery project guidelines](https://docs.google.com/document/d/1IUTTWkps2DtSqaLAJ9bqXMkZg3bKnIn96g-EgX5o1Ag/edit?usp=sharing) are now live! 

    * Note that the project proposal is due Oct 10. <br><br>

* [Link to in-class slides and handouts](https://drive.google.com/drive/folders/17Fm-yEXqtlvGJfFaw6WqywIScW_eZ8m_?usp=drive_link)

* Midterm Reflection is coming up -- complete and meet with me by Oct 9. You can access the [reflection document here](https://docs.google.com/document/d/1Vvhn4R1gUjuunrFFWENReMvucvyaIbzeEJFK0aUpw4M/edit?usp=sharing). The link to my calendar is in the doc. We'll have a 5-min meeting to discuss your responses.

* Exam 1 material finishes this week. Exam 1 is due Oct 2, end of day. Will be available Sep 25.

    * Exams are short-answer, open-note, open-book, untimed. 
    * Use of internet searches not permitted. 
    * Do not discuss with anyone but Angie.
    * Designed to be completed within 75 minutes for a well-prepared student.<br><br>

# Biology Events

* Biology Seminar: Wendy Uhlmann (OC '83), MS, LCGC <br>"Unwinding your DNA: Genetic counseling, genetic testing, and ethical issues", 12:10pm Fri Sep 25, Craig Lecture Hall, <i>Pizza available.</i>

* Branches & Boba - STEM-ing together over Boba! Fri Sep 25, 4:30-6:00pm, Moffett II

* Biology Fall Welcome Event: Wed Sep 30, 4:30-6:00pm with donuts and cider! Outside the Science Center Atrium (inside if rain). Yard games, professors, professors' dogs, friendly faces -- welcoming prospective/interested Biology majors especially!

* Oberlin Shansi (http://www.shansi.org) funds learning experiences between Oberlin and partners in Asia.

    * Fellowships in India, China, Indonesia, Japan, and Vietnam. Applications due Jan 4, 2027 for summer/fall 2027 experiences.
    * AAPI Experience Grants highlight experiences and voices of AAPI communities in North America.
    * In-Asia Grants program applications open for WT and summer 2027; WT project applications due Oct 26.

# Content Videos

* [13-Translation](https://drive.google.com/drive/folders/1hyYSfkHkknSoSUFWH4iqG9serdbD50Oa?usp=drive_link)

* [14-Sex determination](https://drive.google.com/drive/folders/1uVKTC91fryAIm7Ld6JkkZ1HPFjADLPUb?usp=drive_link)

* [15-Inheritance and segregation](https://drive.google.com/drive/folders/1xmfRRvcePwiF_VICihGg9sl-EO98Pp5c?usp=drive_link)

# Assignments

[Quiz 5](404.html)

[Problem Set 5](ps5.html)

# Class Meetings

## Mon Sep 21

No classes (Yom Kippur).

## Wed Sep 23

Komodo dragon case study.

## Fri Sep 25

Quiz 4 solo then corrections with team.

<br>

------------------------------------------------------------------------
