---
title: "BIOL 210 Course Agenda"
date: "Week 3, Sep 16-20"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# Reminders & Events

* Remember to do prob sets, quizzes, and revisions!
* Check your progress using the link under Course Materials dropdown menu
* See assignments handed back in the Student Folders link in Course Materials dropdown menu

* Oberlin Pre-Health Initiative: ObiePhi Community Meeting, Sat 9/21, Moffett Aud, 4-5:30pm. Snacks, games, updates, meet like-minded folks!

* Biology seminar 9/20, 12:10-1:10pm, Craig, "Axon Guidance Signaling: Outside of the Nervous System", Kate Laws, Randolph-Macon College

* GYP-NEXTGEN paid summer research internship in Spain: https://www.jcu.edu/ires (Contact Mike Moore for more info); applications due Nov 1.

* Oberlin Public Health Society (OPHS) along with the Student Leadership and Involvement Office is hosting a University Hospitals CPR training session on Tuesday September 24th from 5-8pm in Wilder Main Lounge. Sign-up link is [here](https://www.signupgenius.com/go/10C0944AEA628A1FBC25-51493315-uhcprtraining#/) and the deadline to sign up is on Friday September 20th. There's a limit of 27 spots. 

# Content Videos

* [07-Mitosis and Binary Fission](https://drive.google.com/drive/folders/1TD2Kl1w4XfPaTKH-Rr4jARDMGWi5Oo9J?usp=drive_link)

* [08-Meiosis](https://drive.google.com/drive/folders/1TvZmfIA1FECe-G12ydwEoMESZpo_tm8B?usp=drive_link)

* [09-Life Cycles](https://drive.google.com/drive/folders/1UC1t0dIPKs3H7rpdKZJkI-3wTdJm_cPV?usp=drive_link)

# Assignments

[Quiz 3](https://docs.google.com/forms/d/e/1FAIpQLSe1c7Kkf5UqH1QIzTxqHBlKg8oEZ75AH84ccSO_qiUPBsbKMA/viewform?usp=sf_link)

[Problem Set 3](ps3.html)

# Class Meetings

## Mon Sep 16

* Case study of Tasmanian devils and DFTD.

## Wed Sep 18

* Finish case study of Tasmanian devils.
* Begin case study of Sex and Komodo Dragon.

## Wed Sep 20

* Finish case study of Sex & Komodo Dragon
* Bead exercise to demonstrate meiosis, mitosis.
