---
title: "BIOL 210 Course Agenda Overview"
date: "Fall 2026"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---

# Weekly Agenda Links

| Agenda | Dates | Topics |
| :--- | :----- | :------------------ |
| [Week 1](agenda-week1.html) | Aug 26-28 | Course Introduction; Biodiversity, Phylogenies, Cells |
| [Week 2](agenda-week2.html) | Aug 31-Sep 04 | Eukarya, Genomes, Eukaryotic genomes |
| Week 3 | Sep 09-11 | Mitosis, Meiosis, Life cycles |
| Week 4 | Sep 14-18 | Genes, Transcription, RNA processing |
| Week 5 | Sep 21-25 | Translation, Sex determination, Inheritance and segregation |
| Week 6 | Sep 28-Oct 02 | Dominance, Independent assortment, Linkage |
| Week 7 | Oct 05-09 | Hardy Weinberg, Detecting evolution, Genetic variation |
| Week 8 | Oct 12-16 | Mutation, Gene flow, Genetic drift |
| - | Oct 19-23 | Fall Break |
| Week 9 | Oct 26-30 | Nonrandom mating, Selection, Heritability |
| Week 10 | Nov 02-06 | Speciation, Population Ecology, Life History |
| Week 11 | Nov 09-13 | Interspecific interactions, Competition |
| Week 12 | Nov 16-20 | Community structure, Ecological succession, Energy flow |
| - | Nov 26-28 | Thanksgiving Break |
| Week 13 | Nov 23-Dec 04 | Biodiversity patterns, Nutrient cycling |
| Week 14 | Dec 07-09 |  Behavior, Learning, Genetics of behavior |

# Groups for first month

For the first month, these will be your assigned groups. **You should sit in a cluster with these folks each day that class meets.** Note: This year's first team theme is creatures of the intertidal zone.

* <b>Anemones:</b> 
* <b>Barnacles:</b> 
* <b>Chitons:</b> 
* <b>Hermit crabs:</b> 
* <b>Limpets:</b> 
* <b>Mussels:</b> 
* <b>Periwinkles:</b> 
* <b>Sea lettuces:</b> 
* <b>Sea stars:</b> 
* <b>Sea urchins:</b> 
