---
title: "BIOL 210 Course Agenda"
date: "Week 10, Nov 3-7"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---

# Reminders

* New Teams!
    * <b>Amaryllis:</b> Arianna, Gabi, Natalie, Jeffrey
    * <b>Bluebell:</b> Mana, Matthew, Nina, Soomin
    * <b>Camellia:</b> Amy, Gabriel, Julia, Sophia
    * <b>Dahlia:</b> Ella, Griffin, Hailey, Koosh
    * <b>Edelweiss:</b> Aimee, Bea, Devyn, Shay
    * <b>Foxglove:</b> Skylar, Dylan, Maddie, Piers
    * <b>Geranium:</b> Aurora, Eleanor, Grant, Liam
    * <b>Hyacinth:</b> Ava, Cash, Iris, Madeleine
    * <b>Iris:</b> Danica, Kristina, Milo, Michael
    * <b>Jasmine:</b> Cleo, Jarrod, Oliver, Riley
    * <b>Kalmia:</b> Amelia, Charlotte, Lex, Micah
    * <b>Lily:</b> Kylie, Toby, Bethany, Charlie

* [Link to in-class slides and handouts](https://drive.google.com/drive/folders/17Fm-yEXqtlvGJfFaw6WqywIScW_eZ8m_?usp=drive_link)

* Conservation Ecology Job Candidate talks this week by Eleanor Diamant
    * Mon Nov 3, 12:10-1:20pm in Craig Aud, Research seminar (pizza available)
    * Mon Nov 3, 4:45-5:30pm in SCTR A155, Teaching demonstration

* Exam 2 material finishes this week.

# Content Videos

* [28-Speciation](https://drive.google.com/drive/folders/1yJUnjnl7Bu8TINEYUvU6xeHLmUEyVjul?usp=drive_link)

* [29-Population ecology](https://drive.google.com/drive/folders/1yLBey1NKFad6GZz7uX3QROpyiPI-ywC0?usp=drive_link)

* [30-Life history](https://drive.google.com/drive/folders/1yQFlYw4q84Ok8NijGkZUnMXSYuOSTHqR?usp=drive_link)

# Assignments

[Quiz 10](https://docs.google.com/forms/d/e/1FAIpQLScDyfJ9tm_FiCAtqjrvvldM6wafu48rRhwZC8qD8VQSCICp1w/viewform?usp=sf_link)

[Problem Set 10](ps10.html)

# Class Meetings

## Mon Nov 3

Case study on speciation and apple maggot flies.

## Wed Nov 5

Case study on population ecology of martens.

## Fri Nov 7

Quiz corrections with teams.


<br>

------------------------------------------------------------------------
