---
title: "BIOL 210 Course Agenda"
date: "Week 4, Sep 14-18"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# Reminders & Events

* [Mastery project guidelines](https://docs.google.com/document/d/1IUTTWkps2DtSqaLAJ9bqXMkZg3bKnIn96g-EgX5o1Ag/edit?usp=sharing) are now live!

* Check your progress using the link under Course Materials dropdown menu

* See assignments handed back in the Student Folders link in Course Materials dropdown menu

* [Link to in-class slides and handouts](https://drive.google.com/drive/folders/17Fm-yEXqtlvGJfFaw6WqywIScW_eZ8m_?usp=drive_link)

* [Link to NYT article](https://www.nytimes.com/2025/09/15/science/ants-species-babies.html) about ants that use another species' DNA to reproduce


# Content Videos

* [10-Genes](https://drive.google.com/drive/folders/1eLzO01lyNV57WvVK-Ie8kH_3eWKHXGcu?usp=drive_link)

* [11-Transcription](https://drive.google.com/drive/folders/1huNxrV8fMPPR74hvxjAqDkf-Yan1GubL?usp=drive_link)

* [RNA processing](https://drive.google.com/drive/folders/1knvr2f7Xf0Pw5J9j45ZtklyrQ3AS3QdJ?usp=drive_link)

# Assignments

[Quiz 3](https://docs.google.com/forms/d/e/1FAIpQLSeBVYqOZ5Sk0CQkfxOqEj7_5bSjNN691eyE4f-34f41pWbaeQ/viewform?usp=sharing&ouid=107508568211857334485)

[Problem Set 4](ps4.html)

# Class Meetings

## Mon Sep 14

* Finish UPGMA exercise (Angie review process).
* Begin case study of Tasmanian devils and DFTD.

## Wed Sep 16

* Finish case study of Tasmanian devils.

* If you want to learn more, there are lots of scientific papers on the subject of DFTD and the devils. Here are a few good overviews of what we know:
    * Storfer et al. 2018. [The devil is in the details: Genomics of transmissible cancers in Tasmanian devils.](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1007098) PLOS Pathogens 14(8):e1007098.
    * Storfer et al. 2025. [The devil in more detail: Eco-evolutionary genomics of Tasmanian devil persistence despite range-wide spread of a fatal, transmissible cancer.](https://doi.org/10.1371/journal.ppat.1013523) PLOS Pathogens 21(9):e1013523.

## Fri Sep 18

* Quiz 3 solo then corrections with team
