---
title: "BIOL 210 Course Agenda"
date: "Week 2, Sep 3-5"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---

# Reminders

* Remember to complete your [grade contract](https://docs.google.com/forms/d/e/1FAIpQLScJdD7yO7pAEkugUMRwGvSrYl5syahIyh271SzR2fy_mscIfA/viewform?usp=sf_link) by Wed Sep 3. Submit via the Assignment Turn-in link above.

* You can check how you are doing in the class using the Check Progress spreadsheet, linked under Course Materials (last item). Type in your T# and watch your results appear!

# Content Videos

* [04-Eukarya](https://drive.google.com/drive/folders/18h_G9z9nqi_LV9Bdq87AZZgCpbEWWCH9?usp=drive_link)

* [05-Genomes](https://drive.google.com/drive/folders/1IhzYhuYcH-58z9h39GZ51fNmXI-n0TO2?usp=drive_link)

* [06-Eukaryotic Genomes](https://drive.google.com/drive/folders/1Il2QzipBuawfY4UMBwP2iQKNM1SP6vBM?usp=drive_link)

# Assignments

[Quiz 2](https://docs.google.com/forms/d/e/1FAIpQLSe03PkgqNcCk6QoPhslpzIQAD6EZWHpb6i-PcE7cla5Q9_7Fg/viewform?usp=sf_link): Complete before 9:00am Fri 9/5 so we can go over in our groups during class.

[Problem Set 2](ps2.html) is due Saturday.


# Class Meetings

Materials presented in class are available in the [Slides and handouts folder](https://drive.google.com/drive/folders/17Fm-yEXqtlvGJfFaw6WqywIScW_eZ8m_?usp=drive_link).

### Groups for first month

For the first month, these will be your assigned groups. **You should sit in a cluster with these folks each day that class meets.** Note: This year's first team theme is carnivores of North America.

* <b>Foxes:</b> Grant, Dylan, Cash, Toby
* <b>Bears:</b> Milo, Bethany, Skylar, Shay
* <b>Badgers:</b> Aurora, Cleo, Micah, Madeleine
* <b>Bobcats:</b> Amy, Michael, Kylie, Arianna
* <b>Lynx:</b> Eleanor, Julia, Hailey, Matthew
* <b>Cougars:</b> Ella, Ava, Gabriel, Danica
* <b>Wolves:</b> Jeffrey, Lex, Koosh, Nina
* <b>Martens:</b> Aimee, Oliver, Charlotte, Piers
* <b>Weasels:</b> Natalie, Maddie, Charlie, Bea
* <b>Coyotes:</b> Devyn, Gabriela, Jarrod, Soomin
* <b>Otters:</b> Griffin, Sophia, Mana, Liam
* <b>Wolverines:</b> Amelia, Kristina, Riley, Iris


## Wed Sep 3

Finish case study "A tale of three lice" (about phylogenetic trees and their uses).

## Fri Sep 5

In teams, complete quizzes 1 and 2 plus corrections. 

