---
title: "BIOL 210 Course Agenda"
date: "Week 1, Aug 27-29"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---

# Reminders

<!-- -   Lab will begin next week, Tue Sep 3 and Wed Sep 4. Lab meets in K119. See the [BIOL 211 Lab website](https://aroles.github.io/biol211/) for more information. -->

The first [problem set is available](ps1.html) and is due Sat Aug 30. You will also want to watch the week 1 content videos (see [agenda week 1](agenda-week1.html)).

# Content Videos

* [01-Biodiversity](https://drive.google.com/drive/folders/13zUXCk4qz2xeb_P53ceg8WtmSEPc9tcy?usp=drive_link)

* [02-Phylogenies](https://drive.google.com/drive/folders/14-ijnaXDxYKokx68eg-DHR0UBlYE_Y66?usp=drive_link)

* [03-Cells](https://drive.google.com/drive/folders/15Eokt5lZOLyt9BOrzobP-NeSGSV5MgeP?usp=drive_link)

# Assignments

[Problem Set 1](ps1.html) and [Quiz 1](https://docs.google.com/forms/d/e/1FAIpQLSclHEk-m9EhZvut1CZE3PJMxdoBZuJkcr-QTfRjAFbJAB4t5A/viewform?usp=sf_link) are due Saturday Aug 30 (end of day). However, it's beneficial for you to watch the content videos and begin the assignments before the week of class.

# Class Meetings

## Wednesday Aug 27

-   First day of class -- go over syllabus, teaching philosophy, course expectations.

-   [Link to slides](https://drive.google.com/drive/folders/17Fm-yEXqtlvGJfFaw6WqywIScW_eZ8m_?usp=drive_link) Requires you to log into your Oberlin account to access.

-   GRADE CONTRACTS: Read this part of the syllabus carefully before filling out the [Grade Contract Form](https://docs.google.com/forms/d/e/1FAIpQLScJdD7yO7pAEkugUMRwGvSrYl5syahIyh271SzR2fy_mscIfA/viewform?usp=sf_link) with your due dates and other info. You are welcome to consult with Angie before submitting your contract. Contracts should be submitted by Wednesday Sept 3rd, end of day.

-   Please fill out the [Getting to Know You](https://docs.google.com/forms/d/e/1FAIpQLScaPNVaX_waXgLUrAUYxIhIfUrhzBsRnpT38HXaxLQhJMlkxQ/viewform?usp=sf_link) form before Wed 9/3.

-   Note: I recommend you watch the videos for next week before Wed 9/3 (see [Week 2 agenda](agenda-week02.html)).

## Friday Aug 29


