---
title: "BIOL 210 Quizzes"
date: "Fall 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---

# Short-Answer Exams

* All exams are take-home, open-note, open-book. This means that you may use any materials provided by the instructor for class as you complete the exam. 

* There is no time limit on the exam. You are free to ask Angie questions as you complete the exam.

* You are NOT allowed to discuss the exam with anyone except Angie Roles, even after you have submitted it (people will complete it at different times and may need to revise). 

* You are not allowed to use internet resources that were not provided by the instructor.

* Violation of any of the above will be reported as an Honor Code violation.

## Exam 1

Exam 1 covers course material through the end of Week 4 (Sep 27). 

You can access [Exam 1 here](https://docs.google.com/document/d/1tlh6gOynHN3jsrQlDlBSNCSHC-iDrr0kIgYzAowZL8Y/edit?usp=sharing). Make a copy for yourself and then type into the doc. Or you can create a separate doc for your responses. Use the link at the top of the website to submit the completed exam.

## Exam 2

Exam 2 covers course material through the end of Week 7 (Oct 18). 

You can access [Exam 2 here](https://docs.google.com/document/d/1qPrOkMtPOAGQ6um0ryvucB-PUNtj23how6juzNthvCo/edit?usp=sharing). Make a copy for yourself and then type into the doc. Or you can create a separate doc for your responses. Use the link at the top of the website to submit the completed exam.

## Exam 3

Exam 3 covers course material through the end of Week 12 (Nov 22). 

You can access [Exam 3 here](https://docs.google.com/document/d/1sq2LNsYKGekiI8ShUm-7_itd7B1G_b44FqmwaKKyd_s/edit?usp=sharing). Make a copy for yourself and then type into the doc. Or you can create a separate doc for your responses. Use the link at the top of the website to submit the completed exam.

## Exam 4 (due by 4pm Dec 16)

Exam 4 covers course material through the end of Week 15 (Dec 11). 

You can access [Exam 4 here](https://docs.google.com/document/d/1g5xNaFgDjosCiYs94WgUOx2e1TLm5BsCIJZLHHa-4uc/edit?usp=sharing). Make a copy for yourself and then type into the doc. Or you can create a separate doc for your responses. Use the link at the top of the website to submit the completed exam.