---
title: "BIOL 210 Problem Sets"
date: "Fall 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---

# General Instructions for Problem Sets

The goal of the problem sets is to give you practice thinking about and working with the concepts that we are covering. You should work alone on this assignment but may freely consult course resources and search the internet (but don't use AI to answer questions).

Before completing a problem set, you should review the content videos for the week and it may be helpful to complete those before the related class periods as well.

Once you have answered the questions and before you turn in your responses, check your work against the answer key (linked for each problem set). If your responses are missing important information or incorrect, you need to correct them, using a different color font and explaining why your original answer was insufficient.

Use the link at the top of this page to turn in your completed assignment. Problem Sets are due on Sundays.


# Weekly Problem Sets

* [PS 1 - due Aug 30](ps1.html)
* [PS 2 - due Sep 6](404.html)
* [PS 3 - due Sep 13](404.html)
* [PS 4 - due Sep 20](404.html)
* [PS 5 - due Sep 27](404.html)
* [PS 6 - due Oct 4](404.html)
* [PS 7 - due Oct 11](404.html)
* Oct 21-25 -- FALL BREAK NO ASSIGNMENT
* [PS 8 - due Oct 25](404.html)
* [PS 9 - due Nov 1](404.html)
* [PS 10 - due Nov 8](404.html)
* [PS 11 - due Nov 15](404.html)
* [PS 12 - due Nov 22](404.html)
* [PS 13 - due Nov 29](404.html)
* [PS 14 - due Dec 9](404.html)