---
title: "BIOL 210 Problem Set 11 KEY"
date: "Week 12, Nov 18-22"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
<text style="background-color:lightcyan">This is the key for PS 11. Before reading this document, you should have completed the problems. Use this key to check and correct your work BEFORE submitting the corrected version via the google form.</text>

<text style="background-color:lightcyan">You should compare your responses with this key and make any changes in another font color. Be sure to explain why you got things wrong (showing that now you understand) as well as providing corrected responses.</text>


# Question Key

<ol>
<li>How do innate behaviors differ from learned behaviors? Does a behavior have to be only innate or only learned? Can there be intermediates?</li>

<text style="background-color:lightcyan">Innate behaviors are those in which no experience with the stimulus is required for the organism to exhibit the ‘correct’ response on the very first exposure. A learned behavior is one in which the organism does not give the optimal response the first time it experiences the stimulus, instead the organism will change its behavior over time, as it gains experience with the stimulus and the consequences of its response. Learned behaviors require experience but not necessarily observing others.</text>

<text style="background-color:lightcyan">There can certainly be intermediates between innate and learned responses. Or some parts of a complex behavior could be innate while other parts might be learned. For example, many organisms that care for their newborn offspring innately know how to take care of their babies BUT many organisms also get better at caring for offspring as they gain experience with it. For example, a number of birds have a lower rate of survival of their chicks for the very first clutch and then a higher rate for the second clutch and perhaps higher still for the third clutch.</text>
<br>

<li>Watch [Video 1: Life of Insects](https://drive.google.com/file/d/1sKbFbXQGXggcvI9GS5C8hOQqk_eoHXUp/view?usp=sharing) (about 8 minutes).</li>
<ol type="a">
<li>Identify a stimulus and response of the ants. What types of communication and signals are being used in this behavior?</li>

<text style="background-color:lightcyan">Stimuli might include the appearance or smell of the seed. (So visual, chemical, and maybe tactile signals.) A response to the stimulus is to pick it up and take it back to the next (treat it like food).</text>
<br>

<li>Given the stimulus or signal you just described, give a proximate explanation for how the stimulus leads to the response.</li>

<text style="background-color:lightcyan">A proximate explanation here would be that the sight or smell of the seed is perceived by the ant, processed in the brain and recognized as familiar (this is food), and then the signals are sent to respond by picking it up and returning it to the nest.</text>
<br>

<li>Reflecting on the segment about the beetle larvae and the digger bees, do you think the behavior of the larvae is innate or learned? Explain your reasoning.</li>

<text style="background-color:lightcyan">Given that the beetle larvae have not had any experience with the stimuli nor the opportunity to observe this behavior, the response of the beetle larvae must be innate.</text>
</ol>
<br>

<li>Watch [Video 2: Wild crows in the city](https://drive.google.com/file/d/1qK6vGh5F5TpWNh7iBxNE5sKAStEn3m8F/view?usp=sharing) (about 2 minutes). In this video, is the behavior of the crows innate or learned? Explain your reasoning.</li>

<text style="background-color:lightcyan">The behavior of the crows in this video is learned. They do not initially know that cars running over the nut will crack it. Nor do they know at the start that using the cross-walk will be safer! In fact, they have probably even learned to fly high and drop the nut on a hard surface. It is experience, and possibly observing the behavior of other crows, that has taught them what works. Interestingly, we might consider whether a tendency for curiosity and trying things out might be an innate feature of crow-ness...</text>
<br>

<li>Why might some behaviors be learned and others be innate? That is, can you think of what conditions are likely to favor a behavior being innate versus conditions that are likely to favor a learned behavior?</li>

<text style="background-color:lightcyan">A behavior which must be done correctly the first time it is needed in order for an organism to survive is likely to be largely innate. Meanwhile, when what you encounter in the environment might be somewhat unpredictable, then it may be favorable to have learned behaviors, as they are able to adjust to the circumstances that the organism faces.</text>
<br>

<li>In thinking about how birdsong develops (see the short reading under Learning), which aspects of the process do you think involve innnate responses? Which aspects do you think involve learned responses? What is the role of genetics? Of environment?</li>

<text style="background-color:lightcyan">The response of making vocalizations at all is likely to be innnate. But the development of a structure to those vocalizations such that a song is produced is likely to involve learning (under normal conditions). In the reading, the example for this is the experiment showing that chaffinches raised without exposure to adult males still sing but their songs are considered abnormal (this would be an innate response). The fact that chicks exposed to recordings of chaffinch song develop normal songs demonstrates a learned aspect.</text>

<text style="background-color:lightcyan">Genetics has a role to play in both innate and learned behaviors as the genome encodes the proteins that are important in perceiving stimuli and generating a response. The example in the reading about birdsong is the FOXP2 gene, which is a transcription factor, turning on or off other genes. Genes like FOXP2 are important in building the neural circuitry that allows an organism to respond innately to a stimulus or to learn a response to a stimulus.</text>

<text style="background-color:lightcyan">One way in which the environment can be crucial with learned responses involves the idea that organisms sometimes can only learn certain behaviors at very particular times in their growth and maturation. In some birds, there is a brief window where song is learned while in others, new songs can be learned throughout life. Thus, the environmental exposures experienced during those critical windows has a huge influence on the response the organism learns to produce.</text>
<br>

<li>Consider how we know that there is a genetic basis to a behavior. Read Sullivan (2005) about the genetics of schizophrenia (5 pages). For example, consider the mental illness schizophrenia whose symptoms can include altered perceptions (e.g., hallucinations, delusions), loss of interest/motivation/enjoyment in daily life, and cognitive symptoms (e.g., reduced attention, concentration, memory).</li>

<ol type="a">
<li>Describe the quantitative evidence that supports a genetic basis for schizophrenia. What patterns or observations suggest that genotype influences whether or not some- one develops schizophrenia?</li>

<text style="background-color:lightcyan">A number of pieces of evidence suggest a genetic basis:</text>

* <text style="background-color:lightcyan">Much higher risk of developing schizophrenia if a close relative has it (family history is a risk factor).</text>

* <text style="background-color:lightcyan">High heritability (81%), determined by comparing monozygotic vs. dizygotic twins.</text>

* <text style="background-color:lightcyan">Adoption studies demonstrate increased risk of schizophrenia if biological parent has it but not if adoptive parent does.</text>

* <text style="background-color:lightcyan">Many GWAS studies have identified genomic locations where genotype appears to correlate with presence/absence of schizophrenia. However, few genomic regions are repeatedly identified by multiple studies, making it difficult to draw broad conclusions. This approach is limited by sample sizes, the size of effect of particular genes (effects can be small), and interactions with environmental risk factors.</text>
<br>

<li>On the flip side, what patterns or observations tell us that genotype is not the ONLY factor influencing disease risk for schizophrenia?</li>

<text style="background-color:lightcyan">Examining Figure 1, we can see that while family history is the largest risk factor for schizophrenia, a variety of environmental factors can also increase risk. Central nervous system damage of newborns has an odds ratio of 7, and infection with rubella has an odds ratio around 5. Meanwhile, we can see that the mother’s environment also matters: prenatal bereavement increases risk with an odds ratio of 6. Other factors increasing maternal stress (famine, flood) have smaller impacts on risk. We can guess that these environmental factors are likely to influence gene expression, especially early on in development, such as the newborn period. Thus, methods that can query the epigenetic state of genes may shed some light on how environmental factors can induce schizophrenia, perhaps even absent any genetic risk factors (disease-causing alleles).</text>
</ol>
</ol>