---
title: "BIOL 210 Problem Set 11"
date: "Week 12, Nov 18-22"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# General Instructions for Problem Sets

The goal of the problem sets is to give you practice thinking about and working with the concepts that we are covering. You may work with others to complete these assignments but should submit your own responses (not copied from someone else's response). 

<b>Before completing a problem set, you should review the content videos for the week and it may be helpful to complete those before the related class periods as well.</b>

Once you have answered the questions and before you turn in your responses, check your work against the answer key (linked for each problem set). If your responses are missing important information or incorrect, you need to correct them, using a different color font and explaining why your original answer was insufficient.

Use the link at the top of this page to turn in your completed assignment, including corrections.

# Related Readings

### REQUIRED READINGS

* About learning: Scitable, [The Development of Birdsong](https://www.nature.com/scitable/knowledge/library/the-development-of-birdsong-16133266/) (short)

* About genetics of behavior: Sullivan, PF. 2005. [The genetics of schizophrenia.](https://doi.org/10.1371/journal.pmed.0020212) PLoS Medicine 2:e212 (5 pages)

### About Behavior

* [The Diversity of Behavior](https://www.nature.com/scitable/knowledge/library/the-diversity-of-behavior-15129167/)

* [What Functions of Living Systems Underlie Behavior?](https://www.nature.com/scitable/knowledge/library/what-functions-of-living-systems-underlie-behavior-13883114/)

### About Learning

* [Organisms without brains can learn, too -- so what does it mean to be a thinking creature?](https://theconversation.com/organisms-without-brains-can-learn-too-so-what-does-it-mean-to-be-a-thinking-creature-214275)

* Dussutour, A. 2021. Learning in single cell organisms. Biochemical and Biophysical Research Communications. https://doi.org/10.1016/j.bbrc.2021.02.018

### About Genetics of Behavior

* Brown et al. 1996. [A defect in nuturing in mice lacking the immediate early gene fosB.](https://doi.org/10.1016/S0092-8674(00)80101-4) Cell 86:297-309. (about 10 pages to read)

    <i>For an example of experimentally studying the genetic basis of behavior, check out this paper on nurturing in mice.</i>



# Questions

<ol>
<li>How do innate behaviors differ from learned behaviors? Does a behavior have to be only innate or only learned? Can there be intermediates?</li>

<br>

<li>Watch [Video 1: Life of Insects](https://drive.google.com/file/d/1sKbFbXQGXggcvI9GS5C8hOQqk_eoHXUp/view?usp=sharing) (about 8 minutes).</li>
<ol type="a">
<li>Identify a stimulus and response of the ants. What types of communication and signals are being used in this behavior?</li>

<br>

<li>Given the stimulus or signal you just described, give a proximate explanation for how the stimulus leads to the response.</li>

<br>

<li>Reflecting on the segment about the beetle larvae and the digger bees, do you think the behavior of the larvae is innate or learned? Explain your reasoning.</li>

</ol>
<br>

<li>Watch [Video 2: Wild crows in the city](https://drive.google.com/file/d/1qK6vGh5F5TpWNh7iBxNE5sKAStEn3m8F/view?usp=sharing) (about 2 minutes). In this video, is the behavior of the crows innate or learned? Explain your reasoning.</li>

<br>

<li>Why might some behaviors be learned and others be innate? That is, can you think of what conditions are likely to favor a behavior being innate versus conditions that are likely to favor a learned behavior?</li>

<br>

<li>In thinking about how birdsong develops (see the short reading under Learning), which aspects of the process do you think involve innnate responses? Which aspects do you think involve learned responses? What is the role of genetics? Of environment?</li>

<br>

<li>Consider how we know that there is a genetic basis to a behavior. Read Sullivan (2005) about the genetics of schizophrenia (5 pages). For example, consider the mental illness schizophrenia whose symptoms can include altered perceptions (e.g., hallucinations, delusions), loss of interest/motivation/enjoyment in daily life, and cognitive symptoms (e.g., reduced attention, concentration, memory).</li>

<ol type="a">
<li>Describe the quantitative evidence that supports a genetic basis for schizophrenia. What patterns or observations suggest that genotype influences whether or not some- one develops schizophrenia?</li>

<br>

<li>On the flip side, what patterns or observations tell us that genotype is not the ONLY factor influencing disease risk for schizophrenia?</li>

</ol>
<br>

<li>Weekly Reflection. Consider this week’s material and reply to one or more of the following prompts:
<ul>
<li> What was confusing or interesting to you about this week’s material?</li>
 
<li> Did you have any key insights while studying this material?</li>

<li> Does anything from this week’s material particularly stick with you?</li>
</ul>
</ol>
<br>


<b>When you are finished, check your responses on the [key for PS10](ps10key.html).</b>

Remember to sign the Honor Code on your assignment.