---
title: "BIOL 210 Problem Set 12 KEY"
date: "Week 13, Nov 25-27"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
<text style="color:blue">This is the key for PS 12. Before reading this document, you should have completed the problems. Use this key to check and correct your work BEFORE submitting the corrected version via the google form.</text>

<text style="color:blue">You should compare your responses with this key and make any changes in another font color. Be sure to explain why you got things wrong (showing that now you understand) as well as providing corrected responses.</text>


# Question Key
<ol>
<li>Refer to one or more of the following readings from Gathering Moss to answer the following questions. Gathering Moss readings are: In the Forest of the Waterbear; Choices; Portrait of Splachnum.</li>
<ol type="a">
<li>Provide 3 examples of non-competitive interspecific interactions that are described in the moss readings. Identify the type of interaction (e.g., commensalism? predation? parasitism?) and which organisms play which roles in the interaction.</li>

<text style="color:blue">Lots of possible responses here!</text><br>

<li>How would you describe the niche of a moss? Does it vary for different species of mosses?</li>

<text style="color:blue">This is most clearly covered in the Portrait of Splachnum chapter; what follows is my response but yours may vary! Mosses can live in very cold places and some very hot places but only if there’s enough water (at least periodically). Many species can survive drought periods in a dormant state and then perk up again when water becomes available. They can’t compete with faster growing angiosperms or gymnosperms but can grow in places with fewer nutrients than most of those competitors. Some mosses are generalists, growing in a wide variety of habitats and conditions while others are specialists, such as the Splachnum ampullulaceum species described in this chapter. Splachnum requires the dung of particular deer species in order to germinate spores, having a preference for “animal nitrogen”. This species then also requires the help of a fly to transport its spores to new dung piles. So yes, the specifics of the niche do differ for different moss species!</text><br>

<li>In these readings from Gathering Moss, do you notice any connections to other topics we’ve covered this semester?</li>

<text style="color:blue">Lots of possible responses here!</text></ol><br>

<li>As described in the content video on Competition, in Gauss’ experiments with competition in Paramecium, the same species always drove the other to extinction. Why is this consistent result expected from competition theory?</li>

<text style="color:blue">Each species has its own specific resource needs and efficiency in acquiring and using those resources. Along with that, that means each different species will have its own carrying capacity (K) for a given environment, containing particular amounts of the resources it needs. As a result, when two species need the same resources but one of them is able to grow more on the same amount of resource (higher resource-use efficiency), then we expect that the more efficient user of resources (more individuals per unit resource per unit time) will “win” in competition. As long as conditions remain the same, we always expect this interaction to end the same way. HOWEVER, if the amount of different resources is changed, that could lead to a different outcome, if the most limited resource now favors the other species. The basic underlying issue is that resources are limited – the same atom of carbon or nitrogen cannot be used for two different purposes at the same time.</text><br>

<li>Consider the different effects of intraspecific versus interspecific competition. Intraspecific competition occurs between members of the same species and tends to result in increased niche breadth of the species. In contrast, interspecific competition (between individuals of different species) is more likely to lead to each competitor species having narrower niches. Explain why intraspecific competition and interspecific competition lead to opposite effects on a species’ niche breadth.</li>

<text style="color:blue">Consider competition within one species (intraspecific). In that case, everyone has extremely similar resource needs so competition is likely to be strong between individuals for any of the most important or most limited resources. As a result, any individual who can use a resource (such as a different food source) that cannot be used by everyone else in that species will have an advantage. This means competition with others of your own species favors broadening your niche, being able to use parts of the environment with less competition.</text>

<text style="color:blue">Now, when we consider competition between two species A and B (interspecific), each species has its own resource needs and efficiency of using those resources. When there are alternative ways to acquire resources within the niche, and some parts of the niche overlap with that of species B, whichever species has higher resource-use efficiency in the niche overlap space will do better in that area. So, if species A only does better than species B at temperatures above 75 deg F, then species A is likely to dominate when the temperature is higher. This will favor species A becoming even better above that temperature, narrowing its niche. Similarly, species B is then at a disadvantage above 75 deg F and it will be favorable for species B to use niche space below that temperature, narrowing its niche.</text><br>

<li>We think of invasive species as a human-facilitated phenomenon (and in many cases that’s totally accurate), but is it really true that the geographic range of a given species has been constant over time? That is, surely natural species have expanded their ranges in the past, such that range expansion is not inherently unnatural. After all, the species that are considered native in this part of Ohio could not have lived here 13,000 years ago when this place was covered with a mile of ice—they must have moved here from elsewhere, without human intervention. <b>Given this, what do you think happens in a community when a new species is introduced? Discuss what types of species interactions might occur and how that might influence the ability of the introduced species to persist in the new area.</b> (You may wish to focus on a particular example to help you illustrate these points.)</li>

<text style="color:blue">A newly arrived species is likely to face competition but perhaps less likely to experience predation/herbivory, parasitism, or mutualism.</text>

<text style="color:blue">When a new species (invasive or not) arrives in a community, it is likely to experience competition with some of the existing species. Interestingly, when a new species first arrives any competition will be interspecies (with other species) and not intraspecific (with itself) since there will not be many individuals of the new species around. The existing species will not have a history of interaction with the new species and so it’s unlikely that the new species experiences mutualism or parasitism when it first arrives (these interactions usually exist between species who have coexisted for a long time). Similarly, the new species may not experience much predation or herbivory if the consumers in the community do not recognize it as a food resource. This might mean that the new species, as long as it can compete for resources, can grow quickly in its new community. However, if the new species required a specific pollinator or a particular microbial partner that it did not bring with it, that could mean the new species would NOT persist well in its new community.</text>

<text style="color:blue">We can also consider not just what happens to the new species (which might evolve rapidly in response to the new conditions), but also what happens to the existing community. Given that the balance of competition for resources may be disrupted by the arrival of a new species, some native species may experience decreases in survival and reproduction if they can no longer acquire the same amount of important resources. Depending on the other interactions that the native species engages in, this could have cascading results for other taxa in the community, for example if a hummingbird-pollinated plant began to decline, that might mean less food for the hummingbird population, which might also then decline. Other species might benefit from the newly introduced species if it does not have much niche overlap but perhaps the introduced species competes with its predator, thus when the predator numbers are reduced, the prey species may increase in numbers – which of course could have cascading effects on the food resource of the prey species!
</text>

<text style="color:blue">The underlying point is that the consequences of species introductions are typically not very predictable and can have dramatic impacts on the native community.</text><br>
</ol>