---
title: "BIOL 210 Problem Set 13 KEY"
date: "Week 14, Dec 2-6"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
<text style="background-color:lightcyan">This is the key for PS 13. Before reading this document, you should have completed the problems. Use this key to check and correct your work BEFORE submitting the corrected version via the google form.</text>

<text style="background-color:lightcyan">You should compare your responses with this key and make any changes in another font color. Be sure to explain why you got things wrong (showing that now you understand) as well as providing corrected responses.</text>


# Question Key

<ol>
<li>Explain the Intermediate Disturbance Hypothesis (IDH). What pattern is explained by this hypothesis and what might give rise to the pattern? How does this relate to topics we have discussed previously?</li>

<text style="background-color:lightcyan">The IDH is one idea that we use to understand why communities differ in species diversity. The basic idea is that the amount of “disturbance” a community experiences influences which species (and how many) can persist there. Let’s consider the two extremes of very disturbed versus little disturbed.</text>

<text style="background-color:lightcyan">If an area is extremely disturbed (either by very frequent disturbances or by less frequent but large disturbances), the hypothesis predicts that very few species can persist with so much disturbance and it is likely that conditions will favor the few species that can survive the disturbance or the few species that can grow fast enough to reproduce before the community is disrupted again.</text>

<text style="background-color:lightcyan">Now if we think about the opposite extreme, a community where disturbances are exceedingly rare, then we expect that competition will dominate and only the few species that are the very best competitors will persist over the long term.</text>

<text style="background-color:lightcyan">And then let’s look at the intermediate condition – the thing emphasized in the hypothesis! In a community that experiences intermediate levels of disturbance (such as common but not huge disruptions), there will be some areas that are more stable and favor strong competitors and other areas that are more recently disrupted and will favor pioneer species (good dispersers, fast growers, but poor competitors)... this intermediate level of disturbance thus fosters the persistence of a variety of life history strategies, overall increasing community diversity.</text>
<br>

<li>We can turn the IDH on its head and consider the way in which community diversity influences the response to a disturbance. That is, a diverse community may be more resilient to disturbance than a species-poor community.</li>
<ol type="a">
<li>What is meant by a community being “resilient” to disturbance? How could we measure this?</li>

<text style="background-color:lightcyan">Generally, when ecologists say that a community is resilient to disturbance, they mean that the productivity of the community is maintained, despite disturbances. Productivity is the amount of biomass that is produced by the community over the course of a growing season. When that value is relatively stable (low coefficient of variation), then we would say the community is more resilient, able to maintain its production of biomass despite disturbances.</text>
<br>

<li>Why might a diverse community be more resilient than a species-poor community?</li>

<text style="background-color:lightcyan">One of the ideas for why a diverse community might be more resilient than a species-poor one is that if some species can’t do well under some conditions, having a diversity of species means it’s likely that another species will be able to grow well under the changed conditions. Consider a monoculture (a community that has only a single species in it, like a corn field). If that monoculture community is hit with a bad drought, and that one species can’t survive well in drought, that will mean biomass goes way down in the drought year. But in a multi-species diverse community, there are likely some members of the community who can thrive during a drought (are adapted to these conditions) and so during the drought year, they will do well and thus maintain biomass production in the community.</text>
</ol><br>


<li>As mentioned in the content video on succession, Clements viewed ecosystems “as analogous to an entire complex organism that, in the event of a disturbance, would pass through a series of stages to return to its climax comunity.” Why is this view inaccurate -- what’s wrong with it? What would be a more accurate way to describe our current understanding of the causes and process of ecological succession?</li>

<text style="background-color:lightcyan">An ecosystem is NOT analagous to an entire organism. Ecosystems do not have mechanisms of maintaining homeostasis, they do not follow a program of development contained in an inherited genome, they do not reproduce themselves, nor do they seem to compete with other ecosystems. Thus, comparing succession in an ecosystem to organismal development from birth to maturity, is not an accurate representation. This comparison suggests that ecosystems are supposed to turn out in a particular way, that they will naturally follow that path every time. While we do describe ecosystems as having properties that emerge from the interactions of their constituent species, we have yet found “rules” that strictly govern how ecosystems are assembled. We do not have evidence that species intentionally change conditions for the benefit of other species and against their own interests (and evolution would not favor this...).</text>

<text style="background-color:lightcyan">There does seem to be a pattern of change in terms of succession – primary succession starts out with species that can survive harsh conditions (pioneer species) and moves seemingly predictably through stages of low vegetation before becoming dominated by shrubs and small trees followed by domination by larger longer-lived trees (strong competitors).</text>

<text style="background-color:lightcyan">One of the strongest arguments against the Clements view comes from what we’ve learned of invasive species. If ecosystems operated as Clements thought, then it would seem that invasive species should never happen – the ecosystem itself would prevent that. Instead, we see that there is nothing special maintaining things as they are – ecosystems can and do tolerate the addition of new species (introduced taxa are not all invaders). Clearly, some taxa change ecosystems more than others do and in ways that we might not appreciate – by altering ecosystem services that we depend upon or reducing species diversity that we value (for aesthetic or other reasons).
</text>

<text style="background-color:lightcyan">Thus, ecological succession results from a dynamic process in which propagules (seeds or fragments of plants) arrive in a place, some of them are able to persist and grow there, their cycles of life and death eventually build soil and change conditions in ways that make them no longer the best competitor, allowing new species to arrive and take root, with the same process occuring of changing conditions with cycles of life and death, until new best competitors are enabled to dominate. Which species are able to disperse into the ecosystem will be critical in determining the possible species composition. When disturbances occur, the competitive balance can be shifted to favor different dominant taxa (ex: an invader arrives) or to alter the composition in more subtle ways (ex: an introduced species becomes part of the community). The properties of the ecosystem result from the activities of its inhabitants and thus alterations to the community structure can also alter ecosystem properties.</text>
<br>

<li>Read either Binding up the Wounds or  Kickapoo. How does the reading connect to what we’ve been covering in class? Give an example of how this reading relates to each of the following.</li>
* competition
* community diversity and structure
* ecological succession

<text style="background-color:lightcyan">Responses will vary!</text>

<li>Describe the flow of energy through a food chain. What are the physical constraints and biological factors that influence the flow?</li>

<text style="background-color:lightcyan">In a food chain, energy ultimately derives from an external source like the sun (there are a few other sources like hydrothermal vents, utilized by chemotrophs). Primary producers (autotrophs) are able to capture some of the energy in sunlight and convert it into biomass via photosynthesis; some energy will also be lost to heat and respiration of primary producers. Primary consumers (heterotrophs) will then eat primary producers, converting some of the energy they contain into consumer biomass but also losing some of it to heat and respiration. Secondary consumers will then eat the primary consumers, etc... When organisms die, decomposers will break down their biomass into simpler components, converting some of the energy into decomposer biomass and losing some to heat and respiration. Decomposers will thus return simpler components (nutrients) back into the system, to be taken up again by primary producers.
</text>

<text style="background-color:lightcyan">The amount of energy captured by producers will limit how much could possibly be available at higher levels, as will the growth rate of the produers (if they grow faster, that potentially provides greater amounts of energy to longer-lived consumers). In addition, the local patterns of temperature and precipitation will influence how much biomass can be supported, with greater biomass typically found with warmer temperatures and greater precipitation (up to a point!). Temperature influences the rate of chemical reactions and adequate precipitation is also typically important in facilitating life-supporting chemical conditions! The local availability of the nutrients needed for organisms to grow (such as nitrogen, phosphorus, potassium, etc) will also limit how much biomass can be supported at each level. A system that is low in nitrogen will not support as many primary producers, for example, despite having sufficient sunlight.</text>
<br>

<li>How do we study energy flow in ecosystems? What do we measure and how can we determine how much of the energy available at one trophic level is transferred to another?</li>

<text style="background-color:lightcyan">To study energy flow in ecosystems we would generally estimate how much biomass is present at different trophic levels. Gross or net primary production, estimated as amount of carbon fixed by plants, is a typical estimate of the energy capacity of ecosystems.</text>

<text style="background-color:lightcyan">
When we want to examine how much of the energy from one trophic level is available to the next trophic level, we examine production efficiency and trophic efficiency. Production efficiency is a method of estimating how much of the energy available to a consumer is actually converted into biomass. At the level of the ecosystem, we can use production efficiency estimates and known numbers of organisms at each trophic level to estimate the trophic level efficiency: of all the biomass energy from one trophic level, how much makes it into biomass at the next level? Typically, trophic efficiency is less than 10% and will mean that total biomass tends to decrease as you move up the food chain, such that top predators are the least abundant category.</text>
</ol>