---
title: "BIOL 210 Problem Set 13"
date: "Week 14, Dec 2-6"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# General Instructions for Problem Sets

The goal of the problem sets is to give you practice thinking about and working with the concepts that we are covering. You may work with others to complete these assignments but should submit your own responses (not copied from someone else's response). 

<b>Before completing a problem set, you should review the content videos for the week and it may be helpful to complete those before the related class periods as well.</b>

Once you have answered the questions and before you turn in your responses, check your work against the answer key (linked for each problem set). If your responses are missing important information or incorrect, you need to correct them, using a different color font and explaining why your original answer was insufficient.

Use the link at the top of this page to turn in your completed assignment, including corrections.

# Related Readings

### REQUIRED READINGS

Read at least ONE of the following chapters from Gathering Moss:

* [Binding up the Wounds: Mosses in Ecological Succession](https://drive.google.com/file/d/1VaaAViI3eMgr0T-j2ylysQJdYREQdHNd/view?usp=sharing) (p. 52-57)

* [Kickapoo](https://drive.google.com/file/d/1pJ5-Bf2UC0Q2bQoufOJ1P9W0ydAQpuCC/view?usp=sharing) (p. 66-71)

### About Community Structure

* Scitable: [Characterizing Communities](https://www.nature.com/scitable/knowledge/library/characterizing-communities-13241173)

* Scitable: [Species with a Large Impact on Community Structure](https://www.nature.com/scitable/knowledge/library/species-with-a-large-impact-on-community-13240710)

* Scitable: [Keystone Species](https://www.nature.com/scitable/knowledge/library/keystone-species-15786127)

* Scitable: [Disturbance and Diversity: An Ecological Chicken and Egg Problem](https://www.nature.com/scitable/knowledge/library/disturbance-and-diversity-an-ecological-chicken-and-13256228)

* Scitable: [Explaining General Patterns in Species Abundance and Distributions](https://www.nature.com/scitable/knowledge/library/explaining-general-patterns-in-species-abundance-and-23162842)

* Scitable: [Neutral Theory of Species Diversity](https://www.nature.com/scitable/knowledge/library/neutral-theory-of-species-diversity-13259703)

### About Ecological Succession

* Scitable: [Succession: A Closer Look](https://www.nature.com/scitable/knowledge/library/succession-a-closer-look-13256638)

* Scitable: [Successional Changes in Communities](https://www.nature.com/scitable/knowledge/library/successional-changes-in-communities-13261649)

### About Energy Flow

* Biology 2e, [Chapter 46. Ecosystems](https://openstax.org/books/biology-2e/pages/46-introduction)

* Scitable: [Food Web: Concept and Applications](https://www.nature.com/scitable/knowledge/library/food-web-concept-and-applications-84077181)

* Scitable: [Trophic Cascades Across Diverse Plant Ecosystems](https://www.nature.com/scitable/knowledge/library/trophic-cascades-across-diverse-plant-ecosystems-80060347)

* Scitable: [Secondary Production, Quantitative Food Webs, and Trophic Position](https://www.nature.com/scitable/knowledge/library/secondary-production-quantitative-food-webs-and-trophic-17653963)


# Questions

<ol>
<li>Explain the Intermediate Disturbance Hypothesis (IDH). What pattern is explained by this hypothesis and what might give rise to the pattern? How does this relate to topics we have discussed previously?</li>

<br>

<li>We can turn the IDH on its head and consider the way in which community diversity influences the response to a disturbance. That is, a diverse community may be more resilient to disturbance than a species-poor community.</li>
<ol type="a">
<li>What is meant by a community being “resilient” to disturbance? How could we measure this?</li>

<br>

<li>Why might a diverse community be more resilient than a species-poor community?</li>

</ol><br>


<li>As mentioned in the content video on succession, Clements viewed ecosystems “as analogous to an entire complex organism that, in the event of a disturbance, would pass through a series of stages to return to its climax comunity.” Why is this view inaccurate -- what’s wrong with it? What would be a more accurate way to describe our current understanding of the causes and process of ecological succession?</li>

<br>

<li>Read either Binding up the Wounds or  Kickapoo. How does the reading connect to what we’ve been covering in class? Give an example of how this reading relates to each of the following.</li>
* competition
* community diversity and structure
* ecological succession

<br>

<li>Describe the flow of energy through a food chain. What are the physical constraints and biological factors that influence the flow?</li>

<br>

<li>How do we study energy flow in ecosystems? What do we measure and how can we determine how much of the energy available at one trophic level is transferred to another?</li>

<br>


<li>Weekly Reflection. Consider this week’s material and reply to one or more of the following prompts:
<ul>
<li> What was confusing or interesting to you about this week’s material?</li>
 
<li> Did you have any key insights while studying this material?</li>

<li> Does anything from this week’s material particularly stick with you?</li>
</ul>
</ol>
<br>


<b>When you are finished, check your responses on the [key for PS13](ps13key.html).</b>

Remember to sign the Honor Code on your assignment.