---
title: "BIOL 210 Problem Set 14 KEY"
date: "Week 15, Dec 9-11"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
<text style="background-color:lightcyan">This is the key for PS 14. Before reading this document, you should have completed the problems. Use this key to check and correct your work BEFORE submitting the corrected version via the google form.</text>

<text style="background-color:lightcyan">You should compare your responses with this key and make any changes in another font color. Be sure to explain why you got things wrong (showing that now you understand) as well as providing corrected responses.</text>


# Question Key

<ol>
<li>What key features do we use to distinguish terrestrial biomes? Aquatic biomes? What types of variation are we highlighting in our definitions of particular biomes, both terrestrial and aquatic?</li>

<text style="background-color:lightcyan">Terrestrial biomes are primarily distinguished by their average annual precipitation and average temperature. So, tropical rain forests have high precipitation and also high temperature. In contrast, high temperature and low precipitation will give you hot desert. Temperature tends to be the axis defining whether a biome is polar, temperate, or tropical in nature. Within a given temperature range, the amount of precipitation defines what type of specific biome is found (desert, grassland, deciduous forest, rain forest).
</text>

<text style="background-color:lightcyan">Aquatic biomes are defined somewhat differently. One major axis is freshwater versus marine (saltwater), defined by the salinity of the environment (with brackish waters being an intermediate zone). Another axis is related to the depth of the water, related to light penetration: the depth to which light penetrates is known as the photic zone, the aphotic zone being the deeper waters where sunlight does not reach. In addition, along a shoreline, we identify the intertidal zone (which is exposed during low tide but submerged during high tide), the neritic zone (constantly submerged but light penetrates), and then the benthic zone (submerged, no light penetration). Temperature is correlated with position along these axes, as is the availability of oxygen such that the benthic zone is the coldest and has the least oxygen.</text>
<br>

<li>What are the essential differences between the movement of carbon, nitrogen, and phosphorus in ecosystems? Organize the info so it’s easy to visually compare them.</li>

<text style="background-color:lightcyan">Carbon (C)</text>

* <text style="background-color:lightcyan">atmosphere: circulates globally where it’s available to photosynthesizers who fix it (C enters the biosphere).</text>

* <text style="background-color:lightcyan">hydrosphere: enters at air-water interface, increased C increases ocean acidity.</text>

* <text style="background-color:lightcyan">lithosphere: C enters from marine deposits (remnants of dead organisms) and from soil organic matter (decomposing organisms). This can be a long-term storage for C (except for when we burn fossil fuels).</text>

* <text style="background-color:lightcyan">biosphere: C enters when photosynthesizers fix it, contribute to their own biomass. Consumers eat producers, C moves through the biosphere. Exits biosphere after decomposition of organisms, enters soil organic matter. </text>

<text style="background-color:lightcyan">Nitrogen (N)</text>

* <text style="background-color:lightcyan">atmosphere: circulates globally, abundant in atmosphere but N2 is not available for most life forms to incorporate so largely unavailable to biosphere. Burning fossil fuels and denitrifying bacteria add N2 to the atmosphere.</text>

* <text style="background-color:lightcyan">hydrosphere: inorganic N circulates in water but is largely unavailable to biosphere in this form (except for N-fixing microbes). Bioavailable N enters the hydrosphere from eutrophication (runoff of fertilizers or other nutrient rich waste flows) and naturally from leaching out of soils.</text>

* <text style="background-color:lightcyan">lithosphere: can enter via soil organic matter.</text>

* <text style="background-color:lightcyan">biosphere: can be fixed from atmosphere by nitrogen-fixing bacteria, producing ammonia/ammonium (or nitrates from nitrifying bacteria) that can be taken up by plants and incorporated into biomass. Over-use of fertilizers (N and P) can lead to eutrophication in aquatic ecosystems. Eutrophication can also occur naturally in lakes and ponds as they age.</text>

<text style="background-color:lightcyan">Phosphorus (P)</text>

* <text style="background-color:lightcyan">atmosphere: No atmospheric circulation (movement of P is local, not global).</text>

* <text style="background-color:lightcyan">hydrosphere: circulates in water, highly available to biosphere but relatively limited in most ecosystems. Use of P in fertilizers has caused increased P inputs in water systems from runoff. Also enters hydrosphere from weathering of rocks (primary storage of P).</text>

* <text style="background-color:lightcyan">lithosphere: primary storage of P on planet. Human mining from rock deposits for use as fertilizers has increased the availability of P in the biosphere. Typically, P would cycle slowly through the lithosphere into the hydrosphere and biosphere. Mining has increased circulating P in hydrosphere and biosphere.</text>

* <text style="background-color:lightcyan">biosphere: inorganic P is taken up by plants and microbes from soil or water, incorporated into biomass. P is typically a limiting nutrient in ecosystems such that P-rich fertilizers increase the productivity of terrestrial and aquatic ecosystems. Over-use of fertilizers (N and P) can lead to eutrophication in aquatic ecosystems. Eutrophication can also occur naturally in lakes and ponds as they age.</text>

<br>

<li>What is the role of decomposition in biogeochemical cycles?</li>

<text style="background-color:lightcyan">Decomposition, carried out primarily by fungi and bacteria/archaea, is critical for breaking down the biomass of dead organisms into less complex molecule. Many of the breakdown products can then be recycled back into the biosphere, once they have been converted into usable forms. Thus, some fraction of the biomass produced in a system will be recycled by decomposers and immediately re-enter the biosphere after decomposition. Without decomposers, a great deal of the nutrients in dead biomass would likely end up in the lithosphere as organic matter accumulated but was not able to be used by other organisms.</text>
<br>

<li>How is anthropogenic disruption of nutrient cycles similar to, and different from, the processes that occur in ecological succession?</li>

<text style="background-color:lightcyan">If you recall the slides from the lecture on Ecological Succession, the availability of different nutrients varies as succession proceeds. Early on, few nutrients are available and not in great quantity; later larger concentrations of nutrients are available thanks to growth and subsequent decomposition. Anthropogenic disruptions that impact nutrient cycles might include things like deforestation, eutrophication, over-harvesting. Like succession, anthropogenic disruptions can alter the availability of nutrients, but in larger ways than is true of something like succession in an old field and typically faster than in primary succession. As a result, anthropogenic disruption can act like a disturbance, suddenly making conditions favorable for r-selected taxa. In situations like eutrophication, this leads to explosive over-growth such that various resources (oxygen) are depleted so greatly as to render the habitat unlivable for a period of time. However, some research shows that with time, ecosystems can be resilient to anthropogenic disruption, such as the experimentally deforested watershed that showed nutrient levels returning to pre-clearance levels within about a decade.</text>
<br>

<li>Weekly Reflection. Consider this week’s material and reply to one or more of the following prompts:
<ul>
<li> What was confusing or interesting to you about this week’s material?</li>
 
<li> Did you have any key insights while studying this material?</li>

<li> Does anything from this week’s material particularly stick with you?</li>
</ul>
</ol>
<br>


<b>When you are finished, check your responses on the [key for PS14](ps14key.html).</b>

Remember to sign the Honor Code on your assignment.