---
title: "BIOL 210 Problem Set 14"
date: "Week 15, Dec 9-11"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# General Instructions for Problem Sets

The goal of the problem sets is to give you practice thinking about and working with the concepts that we are covering. You may work with others to complete these assignments but should submit your own responses (not copied from someone else's response). 

<b>Before completing a problem set, you should review the content videos for the week and it may be helpful to complete those before the related class periods as well.</b>

Once you have answered the questions and before you turn in your responses, check your work against the answer key (linked for each problem set). If your responses are missing important information or incorrect, you need to correct them, using a different color font and explaining why your original answer was insufficient.

Use the link at the top of this page to turn in your completed assignment, including corrections.

# Related Readings

### About Global Biodiversity Patterns

* Biology 2e, [Chapter 44. Ecology and the Biosphere](https://openstax.org/books/biology-2e/pages/44-introduction)

* Scitable: [Rivers and Streams: Life in Flowing Water](https://www.nature.com/scitable/knowledge/library/rivers-and-streams-life-in-flowing-water-23587918)

* Scitable: [Coral Reefs](https://www.nature.com/scitable/knowledge/library/coral-reefs-15786954)

* Scitable: [Terrestrial Biomes](https://www.nature.com/scitable/knowledge/library/terrestrial-biomes-13236757)

### About Nutrient Cycling

* Scitable: [Terrestrial Primary Production: Fuel for Life](https://www.nature.com/scitable/knowledge/library/terrestrial-primary-production-fuel-for-life-17567411)

* Scitable: [The Nitrogen Cycle: Processes, Players, and Human Impact](https://www.nature.com/scitable/knowledge/library/the-nitrogen-cycle-processes-players-and-human-15644632)


# Questions

<ol>
<li>What key features do we use to distinguish terrestrial biomes? Aquatic biomes? What types of variation are we highlighting in our definitions of particular biomes, both terrestrial and aquatic?</li>

<br>

<li>What are the essential differences between the movement of carbon, nitrogen, and phosphorus in ecosystems? Organize the info so it’s easy to visually compare them.</li>

<br>

<li>What is the role of decomposition in biogeochemical cycles?</li>

<br>

<li>How is anthropogenic disruption of nutrient cycles similar to, and different from, the processes that occur in ecological succession?</li>

<br>

<li>Weekly Reflection. Consider this week’s material and reply to one or more of the following prompts:
<ul>
<li> What was confusing or interesting to you about this week’s material?</li>
 
<li> Did you have any key insights while studying this material?</li>

<li> Does anything from this week’s material particularly stick with you?</li>
</ul>
</ol>
<br>


<b>When you are finished, check your responses on the [key for PS14](ps14key.html).</b>

Remember to sign the Honor Code on your assignment.