---
title: "BIOL 210 Problem Set 1 KEY"
date: "Fall 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---

<text style="background-color:yellow">This is the key for PS 1. Before reading this document, you should have completed the problems. Use this key to check and correct your work BEFORE submitting the corrected version via the google form.</text>

<text style="background-color:yellow">You should compare your responses with this key and make any changes in another font color. Be sure to explain why you got things wrong (showing that now you understand) as well as providing corrected responses.</text>

## Question Key
<ol>
<li> Let’s practice using classification and scientific nomenclature. For each of the organisms named below (common names provided), find the scientific name (the binomial nomenclature). Be sure to use the proper formatting!</li>
<ol type="a">
<li> common fruit fly, <br><text style="background-color:yellow"><i>Drosophila melanogaster</i></text></li>
<li> whale shark, <br><text style="background-color:yellow"><i>Rhincodon typus</i></text></li>
<li> Venus flytrap, <br><text style="background-color:yellow"><i>Dionaea muscipula</i></text></li>
<li> magic mushrooms,<br><text style="background-color:yellow"><i>Psilocybe semilanceata</i> or other species (many species in different genera are known by the name magic mushrooms)</text> </li>
</ol>
<br>
<li> As a reminder about the proper formatting, for each of the examples below, describe what is incorrect about the binomial nomenclature.</li>
<ol type="a">
<li> Homo sapiens  <br><text style="background-color:yellow">should be italicized but is not</text></li>
<li> *homo sapiens*  <br><text style="background-color:yellow">The genus name, <i>Homo</i> should be capitalized</text></li>
<li> *Homo Sapiens*  <br><text style="background-color:yellow">The specific epithet, <i>sapiens</i> should not be capitalized</text></li>
<li> *Sapiens* <br><text style="background-color:yellow">The genus name is missing AND the specific epithet should not be capitalized</text></li>
</ol>
<br>
<li>Use the Oak Phylogeny Sheet for questions 3-9. List the terminal taxon or taxa (in this case, species) identified by their most recent common ancestor, that are sister to each oak below.</li>
<ol type="a">
<li> northern red oak is sister to... <br><text style="background-color:yellow">shumard oak</text></li>
<li> post oak is sister to...<br><text style="background-color:yellow">overcup oak</text></li>
<li> black oak is sister to...<br><text style="background-color:yellow">the clade defined by node H, taxa northern red, shumard, pin, and southern red</text></li>
<li> swamp white oak is sister to...<br><text style="background-color:yellow">the clade defined by node C, taxa white oak and bur oak</text></li>
</ol>
<br>
<li>TRUE / FALSE Swamp white oak is most closely related to bur oak. Briefly explain your answer.<br><text style="background-color:yellow">No, swamp white oak is as closely related to bur oak as it is to white oak -- it is equally related to those two species. Those two taxa form the sister group to swamp white oak.</text></li>
<br>
<li>What is the most recent common ancestor of each of the pairs of species listed below? In other words, which node unites the following pairs of species? Write the correct letter for each node next to each pair of species.</li>
<ol type="a">
<li> pin oak & shumard oak  <br><text style="background-color:yellow">node I</text></li>
<li> post oak & southern red oak  <br><text style="background-color:yellow">node D</text></li> 
<li> bur oak & chestnut oak  <br><text style="background-color:yellow">node A</text></li>
</ol>
<br>
<li>Rank the following nodes in Tree 1 in order of increasing age (i.e. youngest to oldest): A, D, K  
<text style="background-color:yellow">(youngest) K, D , A (oldest)</text></li>
<br>

<li> Which terminal taxa are in the clade that is defined by node E?  <br><text style="background-color:yellow">chestnut, blackjack, black, northern red, shumard, pin, southern red</text></li>
<br>
<li> Now find all of the clades in Tree 1. How many are there? List them, using the node to define the clade (so clade defined by node A would be everything on the tree). (Remember that the clade is defined by an ancestor and all of its descendants, so all should be contained in the grouping.)
<text style="background-color:yellow">One clade for each node (11) plus one clade for each terminal taxon (12) so 23 total.</text></li>
<br>
<li> Below are several groups of taxa, some of which form clades in Tree 1 and others of which do not. Place an X next to each group of taxa below that collectively form a clade in Tree 1.
<ol type="a">
<li> white oak, bur oak, swamp white oak, Node B, and all of its descendants  <br><text style="background-color:yellow">This is a clade.</text></li>
<li> southern red oak, post oak, overcup oak, Node K, and all of its descendants  <br><text style="background-color:yellow">Not a clade because not all ancestors are included nor all terminal taxa. If you took out southern red, it would be a clade. But to include southern red you must also have everything descended from node D to make a clade.</text></li>
<li> black oak, northern red oak, shumard oak and all of Node I's descendants  <br><text style="background-color:yellow">Not a clade since the most recent common ancestor of all these taxa is Node G and node G (plus all descendants) is not included.</text></li>
<li> northern red oak, pin oak, southern red oak, and Node H  <br><text style="background-color:yellow">Not a clade. Missing shumard oak plus node H's descendants.</text></li>
<li> post oak, overcup oak  <br><text style="background-color:yellow">Not a clade because you are not including the common ancestor. Must include node K and all its descendants.</text></li>
</ol>
<br>
<li>Referring to the Tree of Life sheet (before filled out):
<ol type="a">
<li> How many taxa on this tree possess vertebrae?  <br><text style="background-color:yellow">4 (numbers 2-5, Lepidosaur, Aves, Mammalia, Actinopterygii)</text></li>
<li> Find the branch where “segmentation” evolved. Is this trait present in all of the descendants of this ancestor?  <br><text style="background-color:yellow">No, Nematoda have lost segmentation</text></li>
<li> Which taxa have alternation of generations but lack vascular tissue?  <br><text style="background-color:yellow">Moss, taxon number 16</text></li>
<li> Which taxa on the tree are segmented but lack a collagen cuticle?  <br><text style="background-color:yellow">Arthropoda and Annelida</text></li>
</ol>
<br>
<li>Finally, complete the table below, using the Tree of Life sheet and other resources (texts, internet, etc) to figure out which number corresponds to which of the following taxa, giving an example species, and listing defining features of the taxon (not the specific species but the larger taxonomic group).</li>
</ul>
<br>

<text style="background-color:yellow">Note that in the table below, defining traits are given as traits mapped on the actual tree where available for the group. The below are examples of defining traits, other traits may also be used to define these groups. You may also wish to see the tree version of the key, [available here](sheets/sci_articles/tolkey.pdf).</text>

```{r tab, echo = FALSE, results = 'asis', message = FALSE, warning = FALSE}
tab <- data.frame(Taxon_Name = c("Actinopterygii", "Amoebozoa", "Angiosperms", "Annelida", "Arthropoda", "Aves", "Bacteria", "Cnidaria", "Echinodermata", "Euglena", "Fern", "Fungi", "Green algae", "Gymnosperms", "Lepidosaur", "Lichen", "Mammalia", "Mollusca", "Moss", "Nematoda", "Paramecium", "Porifera"), Taxon_Number=c(5,1,19,8,10,3,22,11,6,21,17,13,15,18,2,14,4,7,16,9,20,12), Example_Species=c(rep("many possible responses",16),"humans",rep("many possible responses",5)), Defining_Traits=c("fins with thin webbing between bony spines (ray-finned)", "great flexibility in shape", "flowers and fruit", "segmented with collagen cuticle", "jointed appendages", "feathers", "peptidoglycan cell walls", "gelatinous body, possess venomed flagella", "pentaradial symmetry", "flagella", "vascular tissue, spore (no flowers/seeds)", "chitinous cell wall", "chlorophyll, unicellular or colonial", "vascular tissue, naked seeds", "kinetic skull", "symbiosis of algae/cyanobacteria and fungi", "mammary glands", "calcareous shell", "multicellular, no vascular tissue, haploid dominant", "collagen cuticle", "cilia", "spicules"))
                                                                   
knitr::kable(tab)
```

