---
title: "BIOL 210 Problem Set 3"
date: "Week 3, Sep 7-11"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---

[You can download an editable version of this Problem Set here](https://drive.google.com/drive/folders/1nRUFpZG5hHVy7_ULW9vdnKwHFUj5iW7l?usp=drive_link).

# General Instructions for Problem Sets

The goal of the problem sets is to give you practice thinking about and working with the concepts that we are covering. You should work solo to complete these assignments though you may want to do internet searches sometimes. 

<b>Before completing a problem set, you should review the content videos for the week and it may be helpful to complete those before the related class periods as well.</b>

Use the link at the top of this webpage to turn in your completed assignment.

## Problem Set Specifications

To earn an "S":

* Completeness: Every question is thoroughly attempted.
* Accuracy: At least 80% of responses demonstrate correct logical reasoning, accurate quantitative calculations, and correct use of biological terms.
* Integrity & Sources: Citations are included where required, and work adheres to the Honor Code.

# Related Readings

### About Information Transmission (Mitosis and Meiosis)

* Background reading from the open textbook [Biology 2e](https://openstax.org/books/biology-2e/pages/1-introduction) at Openstax -- you can read online or download a PDF.
    * The Cell --> Chapter 10. Cell Reproduction
    * Genetics --> Chapter 11. Meiosis and Sexual Reproduction
    <br><br>

* Schmerler, S and GM Wessel. 2011. [Polar bodies—more a lack of understanding than a lack of respect.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3164815/) 78:3-8.

    <i>This is another awesome review paper describing the diverse ways in which organisms produce and use polar bodies in meiosis. While they degenerate in humans (we are SO boring!), they can be a super important part of the development of others – from flowering plants to parasitic wasps.</i>

* Wilkins, AS, and R Holliday. 2009. [The evolution of meiosis from mitosis.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2621177/) Genetics 181:3-12.

    <i>In this article, the authors present a hypothesis for the evolution of meiosis from mitosis, review the available evidence bearing on the hypothesis, and propose possible tests of the hypothesis.</i>

### About Life Cycles

* Background reading from the open textbook [Biology 2e](https://openstax.org/books/biology-2e/pages/1-introduction) at Openstax -- you can read online or download a PDF.
    * Biological Diversity --> Life cycle information is available in taxon-specific chapters.
    <br><br>

* From Gathering Moss, [The Advantages of Being Small](https://drive.google.com/file/d/1KkPjSXMsXQb4zk1l5PHosNmVspRlqcaB/view?usp=sharing) and [Back to the Pond](https://drive.google.com/file/d/1E7JyiTvrmGsqjXagaWIFG3PHX6ed-aBO/view?usp=sharing)

* Mable, BK, and SP Otto. 1998. [The evolution of life cycles with haploid and diploid phases.](https://www.zoology.ubc.ca/~otto/Reprints/Mable1998.pdf) BioEssays 20:453-462.
    
    <i>This review paper describes what we know about the evolution of variation in the life cycle. I.e., why are some organisms haploid dominant, others diploid dominant and still others have prominent haploid phases AND prominent diploid phases?</i>


# Questions

1. Mitosis evolved before meiosis. What two specific molecular or structural changes to standard mitotic cell division had to occur for the eukaryotic ancestor to achieve meiotic reduction division ($2n \rightarrow n$)?

2. Why is homolog synapsis (pairing) critical during Prophase I of meiosis, but completely absent during mitotic prophase?

3. Consider the potential evolutionary trade-offs of haploid-dominant vs. diploid-dominant life cycles:

    a. What could be one advantage of spending most of a life cycle in the haploid ($n$) state regarding exposure to natural selection?
    b. What could be one advantage of spending most of a life cycle in the diploid ($2n$) state regarding harmful recessive mutations?<br><br>

4. From the list below, identify which of the following stages of the fly life cycle are haploid and which are diploid. Additionally, tell me whether the cells are produced using mitosis or meiosis.

    a. wing cells in an adult fly
    b. unfertilized eggs in a female fly
    c. a newly fertilized fly egg
    d. a young (2nd instar) fly larva body cell
    e. the epidermal cells inside a fly pupa before it hatches into an adult
    f. sperm cells in a male fly's reproductive tract<br><br>

5. Among the related readings are a couple of chapters from Gathering Moss (The Advantages of Being Small and Back to the Pond). In Back to the Pond, Kimmerer talks about the moss life cycle, which is different from that of vascular plants and allows it to adapt to different conditions. Check out the graphic of a moss life cycle from Biology 2e ([link](https://openstax.org/books/biology-2e/pages/25-3-bryophytes)). <b>Describe two ways in which mosses are adapted to their specific environments, compared to larger plants or other organisms.</b>


6. Weekly Reflection. Consider this week’s material and reply to one or more of the following prompts:

    * What was confusing or interesting to you about this week’s material?
    * Did you have any key insights while studying this material?
    * Does anything from this week’s material particularly stick with you?
<br>

Remember to sign the Honor Code on your assignment.