---
title: "BIOL 210 Problem Set 5 KEY"
date: "Week 5, Sep 30-Oct 4"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
<text style="color:blue">This is the key for PS 6. Before reading this document, you should have completed the problems. Use this key to check and correct your work BEFORE submitting the corrected version via the google form.</text>

<text style="color:blue">You should compare your responses with this key and make any changes in another font color. Be sure to explain why you got things wrong (showing that now you understand) as well as providing corrected responses.</text>


# Question Key

We’ve covered biological sex determination in a content video, including the idea that we distinguish between somatic and sex chromosomes. Note that somatic chromosomes are also called autosomes. Some ways somatic and sex chromosomes differ are that the sexes have differing sets of sex chromosomes and the two sex chromosomes do not contain all of the same genetic information as each other (some genes are shared but most are found only on one of the two sex chromosomes). Consider an organism with ZZ/ZW sex determination, where ZZ are male and ZW are female -- this is what birds and some other animals do. 

We can see that there appears to be a difference in copy number (aka dosage) for ZW individuals:
<ul>
<li>ZW and ZZ have 2 copies of all genes on the autosomes.</li>
<li>ZW have only 1 copy of genes on Z or W.</li>
<li>ZZ have 2 copies of Z genes and 0 copies of W genes.</li>
</ul>

That is, for genes found only on Z or only on W, the ZW organism only has one version but for all of the autosomes (like Chromosome 1), the same organism has two copies of every gene. This suggests that when there are sex chromosomes, an organism must have some way to deal with this difference in dosage, some mechanism of <b>dosage compensation</b>. Remember from thinking about the BarH1 gene that the number of copies of a gene can impact the phenotype, it can change gene expression such as by increasing the amount of transcript produced (and thus possibly the amount of protein).

<ol>
<li>Considering what you have learned about transcription and translation, suggest 2 different mechanisms by which gene expression can be altered to achieve similar levels of protein production in ZZ and ZW individuals, for a gene found on the Z chromosome. (Note that telling me “chromatin state could be altered” is not sufficient.) Remember the alternative splicing case study where we discussed things like this!</li>

<text style="color:blue">Multiple possiblities exist, here are a few.</text>

<text style="color:blue">In order to equalize gene expression, a ZZ individual could highly methylate the histones of one Z, which would greatly reduce or prevent gene expression from that chromosome (this would be like the Barr body in human females).</text>

<text style="color:blue">Alternatively, the ZW individual could enhance expression of the genes on their single Z, perhaps producing extra transcription factors to bind enhancers and in- crease expression of individual genes.</text>

<text style="color:blue">Another possibility is that the ZZ individual could reduce transcription on both of its Zs so that it matches the amount of transcription from just one Z.</text><br>
</ol>

In humans, it turns out that having an extra or a missing sex chromosome often has few effects, compared to having an extra or missing autosome. In fact, for 1 in every 1000 live births, the newborn is either XXX (“female”) or XYY (“male”). Such individuals experience typical physical and mental development expected for XX or XY; they may never know of the extra chromosome unless they are karyotyped for some other reason. These individuals are also fertile, producing typical haploid gametes possessing only a single sex chromosome (their children do not inherit their condition).
<br>

<ol start=2>
<li>The question before us is: what happens with gene expression that results in XXX and XYY individuals being just like XX or XY individuals? Propose an explanation for the lack of phenotypic effects of each karyotype, XXX and XYY (the reasons are likely to be different...).</li>

<text style="color:blue">For the XXX individual, remember that XX individuals already shut down one X by forming a Barr body (X-inactivation). In the case of triple-X, two of the X’s form Barr bodies. This would result in the usual phenotypic expression of just one X.</text>

<text style="color:blue">For the XYY individual, it could be that genes on the extra Y are expressed but there aren’t that many genes on the Y-chromosome (only 55) and overexpression of them may just not have that much of an effect. In fact, the National Human Genome Research Institute says that as they age, many men lose the Y chromosome from their cells, without apparent problems.</text><br>

<li>Furthermore, given that the parents of XYY or XXX were XX and XY, what happened during meiosis to yield a YY or XX gamete (thus giving XXX or XYY zygotes)? (Or you can consider: what happens in meiosis to result in the triploid individual producing typical haploid gametes, X or Y?)</li>

<text style="color:blue">The problem in cell division is most likely to have happened during gamete formation in one of the parents. Alternatively, it could occur during very early embryonic development (and thus be present in most of that person’s cells).</text>

<text style="color:blue">Assuming the event occurred during meiosis, for an individual to have XYY, the gamete from their father must have been YY (since females generally have no Y chromosome). For an individual to have XXX, the gamete from one parent must have been XX (possibly either parent since both carry X). This can happen when there is non-disjunction during meiosis I or meiosis II.</text>

<text style="color:blue">If during meiosis I, the homologous pairs would fail to separate and both end up in the same daughter cell, yielding 2 daughter cells with 2 copies of the chromosome and 2 with no copies at the end of the process.</text>

<text style="color:blue">If during meiosis II, sister chromatids fail to separate and you may have 2 regular hap- loid daughter cells and 2 that are aneuploid (one cell with 2 copies of the chromosome and one cell with no copies).</text><br>

<li>Consider Mendel’s Law of Segregation. What observations of his led him to the idea of segregation? What actually happens during meiosis that explains the patterns Mendel observed in pea plants?</li>

<text style="color:blue">Mendel observed that when parents with different phenotypes had offspring, sometimes one of the parental phenotypes seemed to disapear in the immediate offspring (F1 generation) but then might reappear in the F<sub>2</sub> generation, like white flower color. This led him to suggest that the factor causing white flower color and the factor causing purple flower color remained distinct from each other. They didn’t meld together to make something new, rather each version maintained its own integrity and could thus reappear intact in a later generation. Now we know that segregation of factor, or chromosomes, occurs during anaphase I of meiosis, when homologous pairs of chromosomes are separated from each other. This also happens to be the point at which the daughter cells become haploid. As a result of segregation, each gamete (egg or sperm) carries only 1 copy of the flower color gene, either the purple allele or the white allele.</text><br>

<li>From Epigenetics: Provide one genetic and one epigenetic explanation for an individual having increased risk of obesity. If we are doing an experiment, for example with rats or mice, how can we distinguish between an individual that is obese due primarily to genetic factors and one that is obese due primarily to epigenetic factors? Consider what variables you need to control to tell whether a difference is due to genetics compared to due to the environment influencing epigenetics.</li>

<text style="color:blue">Many potential reasonable responses. It’s important to figure out how you can tell the difference between organisms being different due to genetic differences versus due to epigenetic (environment-induced) differences. So, it might be good to have multiple genotypes and multiple environmental conditions (such as a control diet versus one that is thought to lead to obesity). If organisms with the same genotype differ in their propensity to obesity depending on diet, that strongly implicates a role for epigenetic effects on obesity. If genotypes differ in obesity risk even when in the same environment (same diet), that suggests a role for genetic variation in the risk of obesity.</text><br>
</ol>