---
title: "BIOL 210 Problem Set 8 KEY"
date: "Week 9, Oct 28-Nov 1"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
<text style="background-color:lightcyan">This is the key for PS 8. Before reading this document, you should have completed the problems. Use this key to check and correct your work BEFORE submitting the corrected version via the google form.</text>

<text style="background-color:lightcyan">You should compare your responses with this key and make any changes in another font color. Be sure to explain why you got things wrong (showing that now you understand) as well as providing corrected responses.</text>


# Question Key

<ol>
<li>When we think about how evolutionary forces cause genetic change in populations, we need to consider their effects at multiple levels. Let’s do this with the evolutionary force of mutation.</li><br>
<ol type="a">
<li>When a new mutation occurs in an individual, how does it impact variation within that individual’s population (consider average heterozygosity)? Explain.</li>

<text style="background-color:lightcyan">When a mutation occurs in one organism in a population, it is likely to produce a new allele for the locus in which it occurs. This is because mutations are random and thus it is not terribly likely that the exact change will already exist in another individual. That means that a mutation occurring increases genetic variation in the whole population, because a new allele has arisen. Thus, we see a small increase in heterozygosity when a new mutation occurs.</text><br>

<li>When a new mutation occurs in an individual in a population, does it make different populations more genetically alike or more genetically divergent? Explain.</li>

<text style="background-color:lightcyan">If we consider 2 populations (A and B) and a new mutation happens in an individual in population A. From the previous question, we realize that this mutation will not have occurred in population B, since it’s extremely unlikely for the exact same change to happen at random in two populations at once. Thus, we now have a new way in which population A is different from population B, it has this new unique mutation. So, we would say that the new mutation has made the two populations differ more than before, they are now more genetically divergent.</text>
</ol><br>

<li>When we think about the types of mutations that may occur and their possible effects on the organism’s phenotype, we need to consider mutations in light of what we know about gene expression.</li>

<ol type="a">
<li>What types of mutations might be likely to be neutral, having no effect on the organism’s phenotype?</li>

<text style="background-color:lightcyan">Mutations that occur in non-coding regions, with no regulatory function, won’t impact the phenotype. Similarly, we think mutations that change the wobble base in a codon (don’t change the amino acid, synonymous mutations) are also unlikely to alter the organism’s phenotype. </text><br>

<li>What types of mutations are likely to have an effect on phenotype even when you only have one copy? What about those only likely to have an effect on phenotype if you have two copies?</li>

<text style="background-color:lightcyan">Mutations that are likely to change phenotype when you have one copy are likely to be ones that alter amino acids (maybe changing protein function) or that impact how much mRNA is produced (without stopping transcription altogether), like changes to enhancers or silencers. Mutations that will only show in phenotype if you have two copies are most likely to be ones that prevent transcription of a gene altogether or alter the protein so that it doesn’t function at all anymore. As long as you have one working copy, it’s possible that this kind of mutation would not affect phenotype. </text>
</ol><br>

<li>We think of gene flow as a force that keeps populations genetically similar and preserves genetic variation within a population. Is this always a good thing? Can you think of scenarios where gene flow might not be the best thing for the average survival and reproduction of a population?</li>

<text style="background-color:lightcyan">Gene flow can be thought of as the thing that keeps everyone in a species part of that species. However, sometimes a species has many populations found in different environments. In this case, it’s possible that the populations become adapted to their specific conditions – for example the salinity of the soil. If some populations experience high salinity and adapt so that they have a high frequency of alleles that are helpful with high salinity, then it could be harmful to survival if individuals arrive from low salinity environments (and lack the high salinity alleles) and then breed with the high salinity individuals. The offspring will not be as well adapted to high salinity. Without that gene flow, the high salinity population would have higher average survival. </text><br>

<li>Why is the loss of genetic variation due to genetic drift in small populations considered such a serious problem in conservation? Small populations are still experiencing spontaneous mutations, so won’t they be increasing genetic variation that way?</li>

<text style="background-color:lightcyan">Mutation will increase genetic variation only slowly, taking thousands of years to restore genetic variation lost due to drift (which sometimes depletes genetic variation very rapidly). Thus, mutuation is not sufficient to counter drift in the short term.</text>

<text style="background-color:lightcyan">In addition, we typically think that maintaining genetic variation is beneficial in case the environment should change, then there is some chance that some variants will be more successful in the new environment. Of course, an environmental change that favors only some variants will necessarily reduce genetic variation too (but only for the parts of the genome involved in the traits that are favored). </text>

<text style="background-color:lightcyan">The bottom line is that we think genetic variation can act as a buffer, enabling populations to persist when change occurs. Having low genetic variation *can* be a problem but we don’t actually have many examples of it causing a major problem in natural populations (cheetahs lack variation but seem to be doing ok, aside from problems caused by humans). </text><br>

<li>What is a genetic bottleneck? What is the founder effect? How are these phenomena different?</li>

<text style="background-color:lightcyan">A genetic bottleneck is when a sizable population suddenly decreases a lot in size, like in one generation going from thousands to a few hundred (the population size narrows like the neck of a bottle). So this occurs to a population that is living in its usual environment but something happens that rapidly kills many, many individuals at random (natural disaster like a hurricane?). Generally, we might expect a population to grow rapidly after this happens unless the cause of the sudden high mortality is still present. This sudden loss of numbers can cause a random loss of genetic variation (those who survived didn’t do so because they had better genes, it was luck of the draw). </text>

<text style="background-color:lightcyan">A founder effect is when a small subset of a large population leaves and “founds” a new population in a new location, previously uninhabited by this species. The group of founders may be small and therefore at random may not be representative of the genetic variation of the larger population (again, by chance). The new population, being small and in a new area probably without much competition, is expected to grow quickly and thus restore a larger population size – but variation that was not present in the initial founders will still be lacking.</text>

<text style="background-color:lightcyan">As you can see, these phenomena are different in that a genetic bottleneck occurs to an existing population – which could mean that the variation that is lost can not be recovered by other means. In some cases, bottlenecks might impact entire species (if they are not widespread on the planet). In contrast, the founder effect is when a new population arises from a few individuals and they by chance start out with little variation. In this case, there is some possibility that some variation could be recovered IF migrants arrive from other populations. </text><br>


<li>If a population does not experience a genetic bottleneck or a founder effect, will it still change due to genetic drift? Explain.</li>

<text style="background-color:lightcyan">Yes, even without a genetic bottleneck or a founder effect, ALL POPULATIONS ALWAYS EXPERIENCE GENETIC DRIFT. This is a result of the fact that populations are finite in size and there will always be some amount of random change between generations due to chance. However, larger populations will experience smaller amounts of genetic drift (smaller chance changes in allele frequency over generations) as compared to smaller populations.  </text><br>

<li>Genetic drift leads to the loss of genetic variation within populations, increasing the difference from other populations. We often view drift as a force that leads to problems for a population due to the loss of variation. But we should think carefully. Will genetic drift always lead to the loss of genetic variation? Since genetic drift causes populations to become more different from each other, what might be the long-term consequence of that process?</li>

<text style="background-color:lightcyan">Genetic drift, given enough time, will eventually lead to the loss of genetic variation within a population. However, when there are multiple populations (which is most of the time), that means that populations will become more different from each other, thus there may be more genetic variation in the species, even if not in individual populations. In the long-term, two populations could become so different from each other, just by the accumulation of chance changes over time, that they are no longer able to inter-breed and become considered different species.</text>