---
title: "BIOL 210 Problem Set 9"
date: "Week 10, Nov 4-8"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# General Instructions for Problem Sets

The goal of the problem sets is to give you practice thinking about and working with the concepts that we are covering. You may work with others to complete these assignments but should submit your own responses (not copied from someone else's response). 

<b>Before completing a problem set, you should review the content videos for the week and it may be helpful to complete those before the related class periods as well.</b>

Once you have answered the questions and before you turn in your responses, check your work against the answer key (linked for each problem set). If your responses are missing important information or incorrect, you need to correct them, using a different color font and explaining why your original answer was insufficient.

Use the link at the top of this page to turn in your completed assignment, including corrections.

# Related Readings

### About Nonrandom mating

* [Pages 36–43 of Chapter 2. Population genetics I: Genetic variation, random and non- random mating](https://drive.google.com/file/d/1zVP0Vc9e78RY1RYkuooxQsLnm2ZBbtDV/view?usp=sharing), in Conner and Hartl’s A Primer of Ecological Genetics, Sinauer, 2004.


### About Natural selection

* Scitable: [Natural Selection, Genetic Drift, and Gene Flow Do Not Act in Isolation in Natural Populations](https://www.nature.com/scitable/knowledge/library/natural-selection-genetic-drift-and-gene-flow-15186648/)

* [Natural selection at UC Berkeley’s “Understanding Evolution” website.](https://evolution.berkeley.edu/evolution-101/mechanisms-the-processes-of-evolution/natural-selection/) 

    *Read through all the pages following the one linked here until you get to the one for Coevolution. You can stop there (or keep going if you want to!); see the table of contents on the left side of the page. This site is a good resource for basic info on topics in evolution.*
    
* [Another perspective on cancer: Evolution within](https://evolution.berkeley.edu/evo-news/another-perspective-on-cancer-evolution-within/)

* Baym, M, TD Lieberman, ED Kelsic, R Chait, R Gross, I Yelin, and R Kishony. 2016. [Spatiotemporal microbial evolution on antibiotic landscapes.](https://www.science.org/doi/full/10.1126/science.aag0822) Science 353:1147-1151.


### About Heritability

* Scitable: [Adaptation and Phenotypic Variance](https://www.nature.com/scitable/topicpage/adaptation-and-phenotypic-variance-1132)

* Scitable: [Estimating Trait Heritability](https://www.nature.com/scitable/topicpage/estimating-trait-heritability-46889)


# Questions

<ol>
<li>As we have seen, inbreeding can reduce offspring fitness by exposing deleterious recessive alleles. However, some animal breeders practice generations of careful inbreeding within a family, or “line-breeding,” and surprisingly many of the line-bred animals, from champion dogs to prize cows, have normal health and fertility. How can it be possible to continue inbreeding for many generations without experiencing inbreeding depression due to recessive alleles? (Hint: Consider some of the differences between animal breeders and natural selection in the wild.) Generally, if a small population continues to inbreed for many generations, what will happen to the frequency of the deleterious recessive alleles over time?

</ol><br>

<b>For the next five questions, name the evolutionary process(es) being described in each (hypothetical) example, and describe how allele frequencies are likely to change in succeeding generations.</b>

<ol start=2>
<li>A beetle species is introduced to an island covered with dark basaltic rock. On this dark background, dark beetles, TT or Tt, are much more resistant to predation than are light-colored beetles, tt. The dark beetles have a large selective advantage. Both alleles are relatively common in the group of beetles released on the new island.</li><br>

<li>Another beetle population, this time consisting of mostly light beetles and just a few dark beetles, is introduced onto a different island with a mixed substrate of light sand, vegetation, and black basalt. On this island, dark beetles have a selective advantage only on the black basalt.</li><br>

<li>A coral reef fish has two genetically determined types of male, one of which is much smaller (aa) and “sneaks” into larger males’ (AA or Aa) nests to fertilize their females’ eggs. When small males are rare, they have a selective advantage over large males. However, if there are too many small males, large males switch to a more aggressive strategy of nest defense, and small males lose their advantage.</li><br>

<li>In a tropical plant, CC and Cc plants have red flowers and cc plants have yellow flowers. However, Cc plants have defective flower development and produce very few flowers.</li><br>

<li>In a species of bird, individuals with genotype MM are susceptible to avian malaria, Mm and mm birds are resistant to avian malaria, but the mm birds are also vulnerable to avian pox.</li><br>
</ol>

<b>The next four questions are about the evolution of resistance to tetrodotoxin in garter snakes. Use the following info to help you answer the questions.</b><br>

The toxic newt <i>Taricha granulosa</i> and its predator, the garter snake <i>Thamnophis sirtalis</i>, live in forests in western North America. The newt produces the neurotoxin tetrodotoxin (TTX) in its skin; TTX blocks transmission of signals through the nervous system and a newt can produce enough to kill many potential predators (including humans!). The predatory garter snake is the only known potential predator NOT killed by consuming the newt... though it may be affected by the toxin, losing muscle control and mobility for up to 7 hours. Studies in this system have found the following:

* *Snake populations living in the same geographic areas as the toxic newt are resistant to TTX, while garter snake populations in areas without the toxic newt eat other prey and are not resistant to TTX.*

* *In the snake populations with resistance (Benton and Tenmile), the heritability of TTX resistance in garter snakes was estimated to be h<sup>2</sup> = 0.65 in Benton and h<sup>2</sup> = 0.8 in Tenmile.*

* *Experimental attempts to induce resistance by exposing sensitive garter snakes to small amounts of TTX have had no effect.*

* *Resistant snakes have amino acid changes in the SCN4A gene encoding a skeletal muscle voltage-gated sodium channel protein (Nav1.4). These amino acid changes result in greatly reduced binding by TTX in snakes with resistant genotypes.*
<br><br>

<ol start=7>
<li>Is TTX resistance caused by genetic differences or by the environment? How do we know? Be as specific as possible, using the given information.</li><br>

<li>What might explain why the Tenmile (h2 = 0.8) and Benton (h2 = 0.65) populations have different values of heritability for TTX resistance? Do you think all of the snakes in a single population have the same level of resistance?</li><br>

<li>Do you think there is evidence that natural selection is acting (or has acted) on the garter snake populations in terms of resistance to TTX? Explain. (Perhaps discuss the criteria for selection...)</li><br>

<li>What do you think would happen to the frequency of resistance in the Tenmile and Benton populations if the toxic newt went extinct? Explain.</li>

<br>

<li>Weekly Reflection. Consider this week’s material and reply to one or more of the following prompts:
<ul>
<li> What was confusing or interesting to you about this week’s material?</li>
 
<li> Did you have any key insights while studying this material?</li>

<li> Does anything from this week’s material particularly stick with you?</li>
</ul>
</ol>
<br>


<b>When you are finished, check your responses on the [key for PS9](ps9key.html).</b>

Remember to sign the Honor Code on your assignment.