---
title: "BIOL 210 Problem Set 9 KEY"
date: "Week 10, Nov 4-8"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
<text style="background-color:lightcyan">This is the key for PS 9. Before reading this document, you should have completed the problems. Use this key to check and correct your work BEFORE submitting the corrected version via the google form.</text>

<text style="background-color:lightcyan">You should compare your responses with this key and make any changes in another font color. Be sure to explain why you got things wrong (showing that now you understand) as well as providing corrected responses.</text>


# Question Key

<ol>
<li>As we have seen, inbreeding can reduce offspring fitness by exposing deleterious recessive alleles. However, some animal breeders practice generations of careful inbreeding within a family, or “line-breeding,” and surprisingly many of the line-bred animals, from champion dogs to prize cows, have normal health and fertility. How can it be possible to continue inbreeding for many generations without experiencing inbreeding depression due to recessive alleles? (Hint: Consider some of the differences between animal breeders and natural selection in the wild.) Generally, if a small population continues to inbreed for many generations, what will happen to the frequency of the deleterious recessive alleles over time?</li>

<text style="background-color:lightcyan">Inbreeding does not always produce homozygosity for deleterious recessives – it can also produce homozygosity for non-harmful alleles and thereby remove harmful alleles from the population. In fact, if you breed two parents who are heterozygous for the same harmful recessive allele (Tt × Tt), then 75% of the offspring will have at least one T allele and only 25% will be homozygous for the harmful recessive. And breeders won’t use the individuals with low fitness to breed the next generation so they will tend to select parents that are less likely to carry the harmful recessive allele. Eventually, that can mean that the harmful recessives are bred out of the population.</text>

</ol><br>

<b>For the next five questions, name the evolutionary process(es) being described in each (hypothetical) example, and describe how allele frequencies are likely to change in succeeding generations.</b>

<ol start=2>
<li>A beetle species is introduced to an island covered with dark basaltic rock. On this dark background, dark beetles, TT or Tt, are much more resistant to predation than are light-colored beetles, tt. The dark beetles have a large selective advantage. Both alleles are relatively common in the group of beetles released on the new island.</li>

<text style="background-color:lightcyan">There is natural selection occurring – we have variation in beetle color, connected to genotype at the T locus, and color is related to survival (resistance to predation). The dark beetles have an advantage, this is directional selection favoring dark color. Over time, we expect the frequency of the t allele to decrease (and T to increase) and thus to see more dark beetles in the population. In the long term, we expect fixation of the T allele, p=1 and extinction of the t allele.</text><br>

<li>Another beetle population, this time consisting of mostly light beetles and just a few dark beetles, is introduced onto a different island with a mixed substrate of light sand, vegetation, and black basalt. On this island, dark beetles have a selective advantage only on the black basalt.</li>

<text style="background-color:lightcyan">This is a founder event, with only a few dark beetles and possibly not that many founding individuals. The founders have different allele frequencies than the source population did. Here, there is not much advantage for the dark beetles due to the environmental heterogeneity (only an advantage on basalt but there is also lots of non-basalt) so the allele frequencies may change just at random by genetic drift. In fact, it’s possible that the T allele could be lost due to chance. Alternatively, all alleles might be maintained by having advantages in different environments.</text><br>

<li>A coral reef fish has two genetically determined types of male, one of which is much smaller (aa) and “sneaks” into larger males’ (AA or Aa) nests to fertilize their females’ eggs. When small males are rare, they have a selective advantage over large males. However, if there are too many small males, large males switch to a more aggressive strategy of nest defense, and small males lose their advantage.</li>

<text style="background-color:lightcyan">This is also natural selection but it’s frequency-dependent selection, where you only have an advantage when you are rare. The phenotype is male size (or behavior), there is variation associated with genotype, and the less common phenotype has an advantage in reproduction. Over time, we expect to see the most common phenotype fluctuate back and forth between small and large males.</text><br>

<li>In a tropical plant, CC and Cc plants have red flowers and cc plants have yellow flowers. However, Cc plants have defective flower development and produce very few flowers.</li>

<text style="background-color:lightcyan">This is an example of underdominance or heterozygote disadvantage, a type of selection where the heterozygote has the lowest fitness. Over time, we expect to mainly see red flower and yellow flowers, with few heterozygotes. In fact, selection could end up favoring the red and yellow flowers to avoid mating (such as by having different flowering times or different pollinators).</text><br>

<li>In a species of bird, individuals with genotype MM are susceptible to avian malaria, Mm and mm birds are resistant to avian malaria, but the mm birds are also vulnerable to avian pox.</li>

<text style="background-color:lightcyan">When both malaria and pox are present, this is heterozygote advantage or overdominance, a type of selection where the heterozygote has higher fitness than either homozygote. Over time, we’d expect to see all three genotypes persist (if conditions stayed the same)... how common each would be depends on how well the homozygotes (MM and mm) survive and reproduce compared to each other.</text>

<text style="background-color:lightcyan">What if avian malaria is present but avian pox is not? In that case, we would have directional selection favoring mm birds, where m is dominant to M for resistance to malaria. Over time, the frequency of m would increase until fixation, if the conditions stayed the same.</text>

<text style="background-color:lightcyan">What if pox is present but not malaria? Then we have directional selection favoring MM birds, where M is dominant to m for resistance to pox. Over time, the frequency of M would increase until fixation, if the conditions stayed the same.</text><br>
</ol>

<b>The next four questions are about the evolution of resistance to tetrodotoxin in garter snakes. Use the following info to help you answer the questions.</b><br>

The toxic newt <i>Taricha granulosa</i> and its predator, the garter snake <i>Thamnophis sirtalis</i>, live in forests in western North America. The newt produces the neurotoxin tetrodotoxin (TTX) in its skin; TTX blocks transmission of signals through the nervous system and a newt can produce enough to kill many potential predators (including humans!). The predatory garter snake is the only known potential predator NOT killed by consuming the newt... though it may be affected by the toxin, losing muscle control and mobility for up to 7 hours. Studies in this system have found the following:

* *Snake populations living in the same geographic areas as the toxic newt are resistant to TTX, while garter snake populations in areas without the toxic newt eat other prey and are not resistant to TTX.*

* *In the snake populations with resistance (Benton and Tenmile), the heritability of TTX resistance in garter snakes was estimated to be h<sup>2</sup> = 0.65 in Benton and h<sup>2</sup> = 0.8 in Tenmile.*

* *Experimental attempts to induce resistance by exposing sensitive garter snakes to small amounts of TTX have had no effect.*

* *Resistant snakes have amino acid changes in the SCN4A gene encoding a skeletal muscle voltage-gated sodium channel protein (Nav1.4). These amino acid changes result in greatly reduced binding by TTX in snakes with resistant genotypes.*
<br><br>

<ol start=7>
<li>Is TTX resistance caused by genetic differences or by the environment? How do we know? Be as specific as possible, using the given information.</li>

<text style="background-color:lightcyan">We know that resistant snakes have changes in the amino acid sequence of the SCN4A gene and also that exposure to TTX does not induce resistance. These things both suggest that resistance is caused by genetic differences between sensitive and resistant snakes. In addition, the estimates of heritability tell us that resistance is caused by genetic variation and that individuals within populations vary in resistance. Finally, the fact that the heritability values are not 1.0 tells us that the environment must also play some role in resistance.</text><br>

<li>What might explain why the Tenmile (h2 = 0.8) and Benton (h2 = 0.65) populations have different values of heritability for TTX resistance? Do you think all of the snakes in a single population have the same level of resistance?</li>

<text style="background-color:lightcyan">Remembering that $h^2 = V_G/V_P$ and $V_P = V_G +V_E$, we can say Benton and Tenmile have different heritability values due to genetic differences and environmental differences. For example, they could have different allele frequencies for the SCN4A gene. Or they could have different alleles for the gene! Alternatively, there could be environmental factors present in Tenmile that are absent in Benton that influence a snake’s response to TTX. For example, the availability of extracellular potassium ions is known to influence the degree of paralysis experienced such that snakes without the resistance mutations might fare better in an environment where their diet allowed higher levels of extracellular potassium.</text><br>

<li>Do you think there is evidence that natural selection is acting (or has acted) on the garter snake populations in terms of resistance to TTX? Explain. (Perhaps discuss the criteria for selection...)</li>

<text style="background-color:lightcyan">When we want to decide if there is evidence that natural selection could be acting, we need to look for 3 things: (1) there is variation in the phenotype of interest; (2) the phenotypic variation looks to be inherited, there’s a genetic basis for the phenotypic variation; and (3) variation in the phenotype is correlated with fitness (survival and reproduction).</text>

<text style="background-color:lightcyan">In this case, (1) our phenotype is TTX resistance and there is variation – we know not all pops have resistance and there is variation within pops since we have estimates of heritability (must have $V_P$ to get non-zero values). (2) The phenotypic variation appears to be inherited. We know of a related gene (SCN4A) for which resistant snakes have different alleles compared to non-resistant snakes. Even better, we know that the phenotypic variation is inherited because we have pretty high heritability values for the Benton and Tenmile populations. (3) This one is more speculative. We do not seem to have direct evidence that resistant snakes have higher fitness (probably survival) than non-resistant snakes. It seems likely that this would be true but we can’t be certain from this data. If snakes can eat something other than newts, it might not matter whether or not they have resistance so there could not be selection favoring resistance.
</text>

<text style="background-color:lightcyan">I would conclude that we have pretty good evidence that TTX resistance could be experiencing natural selection with the caveat that we haven’t decisively shown that survival and/or reproduction are related to TTX resistance phenotype.</text><br>

<li>What do you think would happen to the frequency of resistance in the Tenmile and Benton populations if the toxic newt went extinct? Explain.</li>

<text style="background-color:lightcyan">If TTX resistance IS favored by selection, then that’s only true when the toxic newt is around to be the source of the selection. If the newt goes extinct, then there is no longer a benefit to having TTX resistance and it’s likely that TTX resistance is costly to the animals, so I’d expect that those without resistance would have higher survival and reproduction in the absence of the newt. Thus, I would predict that extinction of the newt would cause the frequency of resistance in Benton and Tenmile to gradually decrease over time until there are no more resistant snakes in those populations.</text><br>

</ol>