---
title: "BIOL 210 Problem Set 5 KEY"
date: "Week 5, Sep 21-25"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
<text style="background-color:lightcyan">This is the key for PS 6. Before reading this document, you should have completed the problems. Use this key to check and correct your work BEFORE submitting the corrected version via the google form.</text>

<text style="background-color:lightcyan">You should compare your responses with this key and make any changes in another font color. Be sure to explain why you got things wrong (showing that now you understand) as well as providing corrected responses.</text>


# Question Key

1. Translate the following RNA sequence into its amino acid sequence:<br> 5'-AUGGCUCAGUACGCUUGA-3'

<text style="background-color:lightcyan">codons: AUG-GCU-CAG-UAC-GCU-UGA <br> amino acid sequence: Met - Ala - GLn - Tyr - Ala (Stop)</text>

2. Consider the following 2 different mutations that might occur. Identify the mutation and tell me how each impacts protein structure and function?
    a. Mutation 1: 5'-AUGGCUUAGUACGCUUGA-3'
    b. Mutation 2: 5'-AUGUGCUCAGUACGCUUGA-3'

<text style="background-color:lightcyan">For a: This is a nonsense mutation, premature stop codon. <br> 
Codons: AUG | GCU | <b>UAG</b> | UAC | GCU | UGA. <br>
Amino acid sequence is Met - Ala (Stop). <br>
Effect: Replaces glutamine (CAG) with premature stop (UAG) truncating protein chain early.</text>

<text style="background-color:lightcyan">For b: This is a frameshift mutation inserting a U at the fourth position.<br>
Codons: AUG | UGC | UCA | GUA | CGC | UUG | A <br>
Amino Acid Sequence: Met - Cys - Ser - Val - Arg - Leu...<br>
Effect: Shifts the downstream reading frame by one base, completely changing every subsequent amino acid and altering total protein structure.</text>

3. Consider the ZW sex-determination system, found in species including birds and some reptiles. Let's use the komodo dragon as our example. In this system, males are ZZ and females are ZW for the sex chromosomes, all are diploid for all autosomes. Researchers studying dosage compensation measured how much mRNA was produced for 100 autosomal genes and 100 Z-linked genes in both male and female liver tissues.

    a. They predicted that in the absence of dosage compensation, males should produce twice as much mRNA for Z-linked genes compared to females but males and females should produce similar amounts of mRNA for autosomal genes. Explain why the researchers would make this prediction.

<text style="background-color:lightcyan">Expect twice as much on Z because males have 2 copies of Z while females have only 1 copy. In the absence of some compensation mechanism, we expect males and females to have differential expression.</text>

    b. In fact, the researchers observed the ratio for autosomal genes (male : female) was 1.02 : 1 while for Z-linked genes it averaged 1.38 : 1. What might explain this result? How would males end up with an in-between amount of mRNA (more than females but not twice as much)?<br>
 
<text style="background-color:lightcyan">There is some compensation but it does not appear to be similar to the mammalian x-inactivation which impacts the entire chromosome. Gene inactivation must be specific to genes or regions to result in an intermediate level of expression. Some genes are down-regulated in males but they are still producing more transcript than females for many genes. </text> 
 
4. In humans, it turns out that having an extra or a missing sex chromosome often has few effects, compared to having an extra or missing autosome. In fact, for 1 in every 1000 live births, the newborn is either XXX ("female") or XYY ("male"). Such individuals are fertile and experience typical physical and mental development expected for XX or XY.
<br>

    a. The question before us is: what happens with gene expression that results in XXX and XYY individuals being just like XX or XY individuals? Propose an explanation for the lack of phenotypic effects of each karyotype, XXX and XYY (the reasons are likely to be different...).<br>
  
<text style="background-color:lightcyan">For the XXX individual, remember that XX individuals already shut down one X by forming a Barr body (X-inactivation). In the case of triple-X, two of the X’s form Barr bodies. This would result in the usual phenotypic expression of just one X.</text>

<text style="background-color:lightcyan">For the XYY individual, it could be that genes on the extra Y are expressed but there aren’t that many genes on the Y-chromosome (only 55) and overexpression of them may just not have that much of an effect. In fact, the National Human Genome Research Institute says that as they age, many men lose the Y chromosome from their cells, without apparent problems.</text><br>

    b. Furthermore, given that the parents of XYY or XXX were XX and XY, what happened during meiosis to yield a YY or XX gamete (thus giving XXX or XYY zygotes)?<br>
    
<text style="background-color:lightcyan">The problem in cell division is most likely to have happened during gamete formation in one of the parents. Alternatively, it could occur during very early embryonic development (and thus be present in most of that person’s cells).</text>

<text style="background-color:lightcyan">Assuming the event occurred during meiosis, for an individual to have XYY, the gamete from their father must have been YY (since females generally have no Y chromosome). For an individual to have XXX, the gamete from one parent must have been XX (possibly either parent since both carry X). This can happen when there is non-disjunction during meiosis I or meiosis II.</text>

<text style="background-color:lightcyan">If during meiosis I, the homologous pairs would fail to separate and both end up in the same daughter cell, yielding 2 daughter cells with 2 copies of the chromosome and 2 with no copies at the end of the process.</text>

<text style="background-color:lightcyan">If during meiosis II, sister chromatids fail to separate and you may have 2 regular hap- loid daughter cells and 2 that are aneuploid (one cell with 2 copies of the chromosome and one cell with no copies).</text><br>

5. Consider a diploid organism (2n = 4) that is heterozygous for two unlinked genes located on different non-homologous chromosome pairs (AaBb). Gene A is located on a large metacentric chromosome pair, and Gene B is located on a small acrocentric chromosome pair.

    a. Draw 2 separate diagrams representing the two ways that homologous chromosome pairs can align at the metaphase plate in Metaphase I. Clearly distinguish chromosome sizes, indicate duplicated sister chromatids, and label the location of all alleles on the chromatids.

<text style="background-color:lightcyan">Arrangement 1: AA and BB on one side; aa and bb on the other side<br>
Arrangement 2: AA and bb on one side; aa and BB on other side. <br></text>

    b. Independent Assortment: Explain how having two equally likely Metaphase I arrangements physically demonstrates Mendel's Law of Independent Assortment. List the four gamete genotypes produced across both arrangements and state their expected phenotypic ratio.

<text style="background-color:lightcyan">The orientation of the Gene A chromosome pair at the metaphase plate does not influence the orientation of the Gene B chromosome pair. Because both Metaphase I alignments occur with equal probability (50% chance each), meiosis yields four distinct gamete genotypes (AB, Ab, aB, ab) in equal ratios (1:1:1:1).</text>


    c. Segregation: Describe the specific physical event occurring in Anaphase I that represents Mendel's Law of Segregation. Which alleles are being separated from each other?
    
<text style="background-color:lightcyan">The separation of homologous chromosomes during Anaphase I physically separates allele A from allele a (and B from b), ensuring each resulting gamete receives only one allele per locus.</text>

6. From Epigenetics: Provide one genetic and one epigenetic explanation for an individual having increased risk of obesity. If we are doing an experiment, for example with rats or mice, how can we distinguish between an individual that is obese due primarily to genetic factors and one that is obese due primarily to epigenetic factors? Consider what variables you need to control to tell whether a difference is due to genetics compared to due to the environment influencing epigenetics.

<text style="background-color:lightcyan">Many potential reasonable responses. It’s important to figure out how you can tell the difference between organisms being different due to genetic differences versus due to epigenetic (environment-induced) differences. So, it might be good to have multiple genotypes and multiple environmental conditions (such as a control diet versus one that is thought to lead to obesity). If organisms with the same genotype differ in their propensity to obesity depending on diet, that strongly implicates a role for epigenetic effects on obesity. If genotypes differ in obesity risk even when in the same environment (same diet), that suggests a role for genetic variation in the risk of obesity.</text><br>
</ol>

